import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, test } from "@voidzero-dev/vite-plus-test";

import { renderPublishedNoteHTML } from "../src/render-html.ts";

const readStyle = (name: string): string =>
  readFileSync(resolve(process.cwd(), "src/styles", name), "utf8");

describe("Aaron Elegant design system", () => {
  test("ships the required cross-host semantic roles", () => {
    const css = readStyle("aaron-ui-tokens.css");
    for (const token of [
      "--aaron-role-critical",
      "--aaron-role-popout",
      "--aaron-role-strong",
      "--aaron-role-salient",
      "--aaron-role-faded",
      "--aaron-role-subtle",
    ]) {
      expect(css).toContain(token);
    }
    expect(css).not.toContain("--aaronnote-bg");
    expect(css).not.toContain("--aaron-heading-1");
  });

  test("keeps values in the generated token layer and behavior in the adapter", () => {
    const tokens = readStyle("aaron-ui-tokens.css");
    const adapter = readStyle("aaron-ui-elegant.css");
    expect(tokens).toContain("Generated by aaron-ui-export-css-tokens");
    expect(adapter).toContain("var(--aaron-space-4)");
    expect(adapter).toContain(".noema-desktop-titlebar");
    expect(adapter).toContain(".aaronnote-status-pill");
    expect(adapter).not.toContain(".cm-content");
    expect(adapter).not.toContain(".cm-editor");
  });

  test("published notes load tokens before the Elegant adapter", () => {
    const html = renderPublishedNoteHTML("# Title", { title: "Title" });
    const tokenIndex = html.indexOf("aaron-ui-tokens.css");
    const adapterIndex = html.indexOf("aaron-ui-elegant.css");
    expect(tokenIndex).toBeGreaterThan(-1);
    expect(adapterIndex).toBeGreaterThan(tokenIndex);
  });
});
