;;; noema-agenda-capture-tests.el --- Shared capture menu tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'noema-agenda-capture)

(defun noema-capture-test--catalog ()
  '((revision . "catalog-v1")
    (templates . [((id . "deadline") (key . "d") (name . "Deadline") (file . "reviews.md") (scope . "selected")
                   (defaults . ((prio . "B")))
                   (fields . [((name . "text") (label . "Task") (kind . "text") (required . t))
                              ((name . "ddl") (label . "Deadline") (kind . "date") (required . t))
                              ((name . "prio") (label . "Priority") (kind . "choice") (choices . ["" "A" "B"]) (required . nil))]))])))

(ert-deftest noema-capture-uses-reviewed-template-fields-and-active-scope ()
  (with-temp-buffer
    (setq noema-agenda--snapshot '((scopes . [((id . "knowledge") (kind . "knowledge") (root . "/vault"))
                                            ((id . "p") (kind . "project") (root . "/project"))])))
    (cl-letf (((symbol-function 'completing-read)
               (lambda (prompt choices &rest _)
                 (cond ((equal prompt "Capture scope: ") "/project")
                       ((equal prompt "Priority: ") "B")
                       (t (caar choices)))))
              ((symbol-function 'read-string) (lambda (&rest _) "Review"))
              ((symbol-function 'org-read-date) (lambda (&rest _) "2026-09-20")))
      (let ((body (noema-agenda--capture-template-body (noema-capture-test--catalog) nil)))
        (should (equal (alist-get 'templateId body) "deadline"))
        (should (equal (alist-get 'templateRevision body) "catalog-v1"))
        (should (equal (alist-get 'scopeId body) "p"))
        (should (equal (alist-get 'file body) "/project/reviews.md"))
        (should (equal (alist-get 'text body) "Review"))
        (should (equal (alist-get 'ddl body) "2026-09-20"))
        (should (equal (alist-get 'prio body) "B"))))))

(ert-deftest noema-capture-menu-uses-the-protected-source-writer ()
  (let ((buffer (generate-new-buffer " *capture*")) request)
    (unwind-protect
        (save-window-excursion
          (switch-to-buffer buffer)
          (noema-agenda-mode)
          (cl-letf (((symbol-function 'noema-agenda--call)
                     (lambda (op _body callback)
                       (should (equal op "capture-templates"))
                       (funcall callback (noema-capture-test--catalog) nil)))
                    ((symbol-function 'noema-agenda--capture-template-body)
                     (lambda (_catalog _choose-file) '((text . "Review") (file . "/project/reviews.md") (templateId . "deadline"))))
                    ((symbol-function 'noema-agenda--write)
                     (lambda (op body files _callback) (setq request (list op body files)))))
            (noema-agenda-capture-menu)
            (should (equal request '("capture" ((text . "Review") (file . "/project/reviews.md") (templateId . "deadline")) ("/project/reviews.md"))))))
      (kill-buffer buffer))))

(ert-deftest noema-capture-menu-does-not-open-after-its-buffer-was-closed ()
  (let ((buffer (generate-new-buffer " *capture*")) callback)
    (unwind-protect
        (cl-letf (((symbol-function 'noema-agenda--call) (lambda (_op _body cb) (setq callback cb)))
                  ((symbol-function 'noema-agenda--capture-template-body) (lambda (&rest _) (ert-fail "closed capture"))))
          (with-current-buffer buffer (noema-agenda-capture-menu))
          (kill-buffer buffer)
          (funcall callback (noema-capture-test--catalog) nil))
      (when (buffer-live-p buffer) (kill-buffer buffer)))))

(ert-deftest noema-capture-reopens-draft-with-current-template-revision ()
  (with-temp-buffer
    (setq noema-agenda--snapshot '((scopes . [((id . "knowledge") (kind . "knowledge") (root . "/vault"))]))
          noema-agenda--capture-draft '((templateId . "deadline") (templateRevision . "old")
                                        (scopeId . "knowledge") (file . "/vault/other.md")
                                        (text . "Retained") (ddl . "2026-09-21") (prio . "A")))
    (cl-letf (((symbol-function 'completing-read)
               (lambda (prompt choices _predicate _require-match &optional initial _history default &rest _)
                 (if (equal prompt "Priority: ") initial (or default (caar choices)))))
              ((symbol-function 'read-string) (lambda (_prompt initial &rest _) initial))
              ((symbol-function 'org-read-date) (lambda (_a _b _c _prompt _time initial &rest _) initial)))
      (let ((body (noema-agenda--capture-template-body (noema-capture-test--catalog) nil)))
        (should (equal (alist-get 'templateRevision body) "catalog-v1"))
        (dolist (field '((text . "Retained") (ddl . "2026-09-21") (prio . "A") (file . "/vault/other.md")))
          (should (equal (alist-get (car field) body) (cdr field))))))))

(ert-deftest noema-capture-retains-failed-draft-and-prevents-duplicate-writes ()
  (let ((buffer (generate-new-buffer " *capture failure*")) callback)
    (unwind-protect
        (save-window-excursion
          (switch-to-buffer buffer)
          (cl-letf (((symbol-function 'noema-agenda--call)
                     (lambda (_op _body cb) (funcall cb (noema-capture-test--catalog) nil)))
                    ((symbol-function 'noema-agenda--capture-template-body)
                     (lambda (&rest _) '((text . "Keep") (file . "/vault/tasks.md"))))
                    ((symbol-function 'noema-agenda--write)
                     (lambda (_op _body _files cb) (setq callback cb))))
            (noema-agenda-capture-menu)
            (should-error (noema-agenda-capture-menu) :type 'user-error)
            (funcall callback nil '((message . "Excluded")))
            (should-not noema-agenda--capture-saving)
            (should (equal (alist-get 'text noema-agenda--capture-draft) "Keep"))
            (noema-agenda-capture-menu)
            (funcall callback '((todo . ((uid . "saved")))) nil)
            (should-not noema-agenda--capture-draft)
            (should (equal noema-agenda--preferred-uid "saved"))))
      (kill-buffer buffer))))
