;;; noema-agenda-tests.el --- Native Agenda contract tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'noema-agenda)
(require 'noema-research)
(require 'noema-research-mode)

(defun noema-agenda-test--snapshot ()
  (copy-tree '((todos . [((uid . "one") (id . "#abc123") (scopeId . "knowledge")
               (file . "/vault/note.md") (source . "@@todo [Native]{id: abc123}")
               (sourceRef . ((revision . "rev1")))
               (text . "Native task") (status . "todo") (effectiveStatus . "todo")
               (noteTitle . "Research") (canon . ((prio . "A") (tags . "proof"))))
              ((uid . "two") (id . "#abc124") (scopeId . "knowledge")
               (text . "Finished task") (status . "done") (effectiveStatus . "done")
               (noteTitle . "Research") (canon . ((prio . "D"))))])
    (days . [((date . "2026-09-15")
              (entries . [((todoId . "one") (kind . "scheduled") (label . "Scheduled") (time . "10:00"))
                           ((todoId . "two") (kind . "deadline") (label . "Deadline"))]))])
    (errors . [])) t))

(defmacro noema-agenda-test--with-buffer (&rest body)
  `(with-temp-buffer
     (noema-agenda-mode)
     (setq noema-agenda--from "2026-09-15")
     (noema-agenda--render (noema-agenda-test--snapshot))
     ,@body))

(ert-deftest noema-agenda-native-render-never-converts-to-org ()
  (let ((org-agenda-files '("/unrelated/personal.org")))
    (cl-letf (((symbol-function 'make-temp-file) (lambda (&rest _) (ert-fail "temporary file")))
              ((symbol-function 'write-region) (lambda (&rest _) (ert-fail "write")))
              ((symbol-function 'org-mode) (lambda (&rest _) (ert-fail "Org source buffer")))
              ((symbol-function 'org-agenda-list) (lambda (&rest _) (ert-fail "Org scanner")))
              ((symbol-function 'org-agenda-get-day-entries) (lambda (&rest _) (ert-fail "Org source entries"))))
      (noema-agenda-test--with-buffer
       (should (string-match-p "10:00" (buffer-string)))
       (should (string-match-p "TODO.*Native task" (buffer-string)))
       (goto-char (point-min)) (search-forward "Native task")
       (should (equal "one" (noema-agenda--get (noema-agenda-item-at-point) 'uid)))
       (should-not (get-text-property (point) 'org-marker))
       (should (equal org-agenda-files '("/unrelated/personal.org")))))))

(ert-deftest noema-agenda-default-includes-unscheduled-roam-tasks ()
  "The default Org-style view must not hide parsed tasks without dates."
  (with-temp-buffer
    (noema-agenda-mode)
    (setq noema-agenda--from "2026-09-16")
    (noema-agenda--render
     '((todos . [((uid . "roam-open") (id . "#roam-open")
                  (scopeId . "knowledge") (file . "/vault/research.md")
                  (text . "Unscheduled Roam task") (status . "todo")
                  (effectiveStatus . "todo") (canon . ((prio . "B"))))])
       (days . [((date . "2026-09-16") (entries . []))])
       (errors . [])))
    (should (equal noema-agenda--blocks '((agenda) (todo))))
    (should (string-match-p "Tasks" (buffer-string)))
    (should (string-match-p "TODO.*Unscheduled Roam task" (buffer-string)))))

(ert-deftest noema-agenda-has-no-inherited-org-source-writers ()
  (noema-agenda-test--with-buffer
   (should (eq (key-binding (kbd "t")) #'noema-agenda-complete))
   (should (eq (key-binding (kbd "s")) #'noema-agenda-schedule))
   (should (eq (key-binding (kbd "r")) #'noema-agenda-refresh))
   (should (eq (key-binding (kbd "R")) #'noema-agenda-toggle-knowledge))
   (should (eq (key-binding (kbd ".")) #'noema-agenda-toggle-completed))
   (should (eq (key-binding (kbd "v .")) #'noema-agenda-today))
   (should (eq (key-binding (kbd "v r")) #'noema-agenda-repeat))
   (should-not (where-is-internal #'org-agenda-todo (current-local-map)))
   (should-not (where-is-internal #'org-agenda-clock-in (current-local-map)))
   (should-not (where-is-internal #'org-agenda-archive (current-local-map)))))

(ert-deftest noema-agenda-uses-compact-source-label-and-visible-todo-title ()
  (noema-agenda-test--with-buffer
   (should (string-match-p "note:.*Native task" (buffer-string)))
   (should-not (string-match-p "Research[[:space:]]+.*Native task" (buffer-string)))))

(ert-deftest noema-agenda-source-label-counts-files-instead-of-tasks ()
  (with-temp-buffer
    (noema-agenda-mode)
    (let* ((snapshot (noema-agenda-test--snapshot))
           (first (aref (alist-get 'todos snapshot) 0))
           (second (copy-tree first)))
      (setf (alist-get 'uid second) "same-file-two"
            (alist-get 'text second) "Second native task"
            (alist-get 'todos snapshot) (vector first second))
      (setq noema-agenda--from "2026-09-15"
            noema-agenda--blocks '((todo)))
      (noema-agenda--render snapshot)
      (should (string-match-p "note:.*Native task" (buffer-string)))
      (should (string-match-p "note:.*Second native task" (buffer-string)))
      (should-not (string-match-p "vault/note" (buffer-string))))))

(ert-deftest noema-agenda-toggle-knowledge-keeps-the-entered-project ()
  (noema-agenda-test--with-buffer
   (let ((noema-agenda--project-scope "project:demo") refreshed)
     (setq noema-agenda--knowledge-visible t
           noema-agenda--scopes '("knowledge" "project:demo"))
     (cl-letf (((symbol-function 'noema-agenda-refresh) (lambda (&optional _) (setq refreshed t))))
       (noema-agenda-toggle-knowledge)
       (should refreshed)
       (should-not noema-agenda--knowledge-visible)
       (should (equal noema-agenda--scopes '("project:demo")))
       (noema-agenda-toggle-knowledge)
       (should noema-agenda--knowledge-visible)
       (should (equal noema-agenda--scopes '("knowledge" "project:demo")))))))

(ert-deftest noema-agenda-dashboard-always-requests-roam-and-entered-project ()
  (with-temp-buffer
    (let ((noema-agenda--project-scope "project:demo") request)
      (setq-local noema-agenda--knowledge-visible t)
      (cl-letf (((symbol-function 'noema-agenda--call)
                 (lambda (operation body _callback)
                   (setq request (cons operation body)))))
        (noema-agenda-dashboard-query #'ignore)
        (should (equal (car request) "query"))
        (should (equal (append (alist-get 'scopes (cdr request)) nil)
                       '("knowledge" "project:demo")))))))

(ert-deftest noema-agenda-hides-completed-by-default-and-dot-toggles-locally ()
  (noema-agenda-test--with-buffer
   (should-not (string-match-p "Finished task" (buffer-string)))
   (cl-letf (((symbol-function 'noema-agenda--call)
              (lambda (&rest _) (ert-fail "completed toggle queried sources"))))
     (noema-agenda-toggle-completed)
     (should noema-agenda--show-completed)
     (should (string-match-p "DONE.*Finished task" (buffer-string)))
     (noema-agenda-toggle-completed)
     (should-not noema-agenda--show-completed)
     (should-not (string-match-p "Finished task" (buffer-string))))))

(ert-deftest noema-agenda-mutation-uses-native-identity-and-revision ()
  (noema-agenda-test--with-buffer
   (let (request)
     (cl-letf (((symbol-function 'noema-agenda--call)
                (lambda (operation body _callback) (setq request (cons operation body)))))
       (goto-char (point-min)) (search-forward "Native task")
       (noema-agenda-complete)
       (should (equal (car request) "patch"))
       (should (equal (alist-get 'uid (cdr request)) "one"))
       (should (equal (alist-get 'revision (cdr request)) "rev1"))
       (should (equal (alist-get 'patch (cdr request)) '((op . "complete"))))))))

(ert-deftest noema-agenda-filter-and-custom-blocks-need-no-io ()
  (noema-agenda-test--with-buffer
   (cl-letf (((symbol-function 'noema-agenda--call) (lambda (&rest _) (ert-fail "query for local filter"))))
     (noema-agenda-todos)
     (should-not (string-match-p "Finished task" (buffer-string)))
     (noema-agenda-filter "missing")
     (should-not (string-match-p "Native task" (buffer-string)))
     (noema-agenda-filter "native")
     (should (string-match-p "Native task" (buffer-string)))
     (noema-agenda-filter-tag "proof")
     (should (string-match-p "Native task" (buffer-string)))
     (noema-agenda-filter-tag "other")
     (should-not (string-match-p "Native task" (buffer-string))))))

(ert-deftest noema-agenda-hidden-notification-only-marks-dirty ()
  (noema-agenda-test--with-buffer
   (cl-letf (((symbol-function 'noema-agenda--call) (lambda (&rest _) (ert-fail "hidden background query"))))
     (noema-agenda-handle-change nil)
     (should noema-agenda--dirty))))

(ert-deftest noema-agenda-coalesces-events-during-query ()
  (noema-agenda-test--with-buffer
   (let ((calls 0) callback)
     (cl-letf (((symbol-function 'noema-agenda--call)
                (lambda (_operation _body done) (cl-incf calls) (setq callback done))))
       (noema-agenda-refresh)
       (dotimes (_ 20) (noema-agenda-refresh))
       (should (= calls 1))
       (funcall callback (noema-agenda-test--snapshot) nil)
       (should (= calls 2))
       (funcall callback (noema-agenda-test--snapshot) nil)
       (should (= calls 2))
       (should-not noema-agenda--pending)))))

(ert-deftest noema-agenda-worknode-visible-syntax-roundtrips-with-dag-and-output ()
  (let* ((file (expand-file-name "../poc/org-agenda/example.noema"
                                  (file-name-directory (locate-library "noema-agenda")))))
    (with-temp-buffer
      (insert-file-contents file)
      (let* ((document (json-parse-buffer :object-type 'hash-table :array-type 'array
                                         :null-object :null :false-object :false))
             (outputs (json-serialize (gethash "outputs" (aref (gethash "cells" document) 2))))
             (dependencies (json-serialize (gethash "dependencies" (gethash "noema_research" (gethash "metadata" document)))))
             (patch (make-hash-table :test #'equal)))
        (should-not (noema-research--directive-errors document))
        (puthash "sche" "2026-09-16 10:30" patch)
        (noema-research-set-agenda document "wn_proof" patch)
        (should-not (plist-get (noema-research-validate document) :errors))
        (let* ((roundtrip (json-parse-string (json-serialize document) :object-type 'hash-table :array-type 'array
                                            :null-object :null :false-object :false))
               (cell (noema-research-primary-cell roundtrip "wn_proof"))
               (agenda (noema-research-agenda-directive (noema-research-cell-source cell) "work")))
          (should (equal (gethash "sche" agenda) "2026-09-16 10:30"))
          (should (string-match-p "@@todo \\[Ask the agent" (noema-research-cell-source cell)))
          (should (equal outputs (json-serialize (gethash "outputs" cell))))
          (should-not (gethash "agenda" (noema-research-find-work-node roundtrip "wn_proof")))
          (should (equal dependencies (json-serialize (gethash "dependencies" (gethash "noema_research" (gethash "metadata" roundtrip)))))))
        (noema-research-set-agenda document "wn_proof" nil)
        (should-not (noema-research-agenda-directive
                     (noema-research-cell-source (noema-research-primary-cell document "wn_proof"))
                     "work"))))))

(ert-deftest noema-agenda-discards-old-query-after-changing-date-range ()
  (noema-agenda-test--with-buffer
   (let (callback rendered)
     (cl-letf (((symbol-function 'noema-agenda--call)
                (lambda (_operation _body done) (setq callback done)))
               ((symbol-function 'noema-agenda--render) (lambda (_snapshot) (setq rendered t))))
       (noema-agenda-refresh)
       (noema-agenda-next)
       (funcall callback (noema-agenda-test--snapshot) nil)
       (should-not rendered)
       (should noema-agenda--pending)))))

(ert-deftest noema-agenda-worknode-rejects-invalid-metadata ()
  (dolist (raw '("null" "[]" "{\"sche\":\"yesterday\"}" "{\"prio\":\"urgent\"}"
                 "{\"effort\":\"nonsense\"}" "{\"status\":\"done\"}" "{\"repeat\":\"+1d\"}"))
    (should (noema-research-agenda-errors (json-parse-string raw) "work")))
  (should-not (noema-research-agenda-errors
               (json-parse-string "{\"effort\":\"0m\",\"sche\":\"2026-09-15\",\"project\":\"Proof\"}") "work")))

(ert-deftest noema-agenda-reacquires-only-current-project-after-host-restart ()
  (let ((noema-agenda--project-root "/project/")
        (noema-agenda--project-scope "old-scope")
        (noema-agenda--project-lease "old-lease")
        (noema-agenda--project-request 0)
        (noema-agenda--reconnect nil)
        calls)
    (cl-letf (((symbol-function 'noema-agenda--call)
               (lambda (operation body _callback) (push (cons operation body) calls))))
      (noema-agenda-host-stopped)
      (should-not calls)
      (should-not noema-agenda--project-scope)
      (noema-agenda-host-ready)
      (should (equal (caar calls) "enter"))
      (should (equal (alist-get 'root (cdar calls)) "/project/"))
      (should (= (length calls) 1)))))


(ert-deftest noema-agenda-project-placement-and-stale-acquisition ()
  (let ((noema-agenda--project-root nil)
        (noema-agenda--project-scope nil)
        (noema-agenda--project-lease nil)
        (noema-agenda--project-request 0)
        (noema-agenda-project-root-function (lambda (_root) "/client/project/"))
        calls callbacks)
    (cl-letf (((symbol-function 'noema-agenda--update-scopes) #'ignore)
              ((symbol-function 'noema-agenda--call)
               (lambda (operation body callback)
                 (push (cons operation body) calls)
                 (when (equal operation "enter") (push callback callbacks)))))
      (noema-agenda-activate-project "/fs:shared:/project/")
      (should (equal (alist-get 'root (cdar calls)) "/client/project/"))
      (let ((lease (alist-get 'lease (cdar calls))))
        (noema-agenda-activate-project nil)
        (funcall (car callbacks) '((id . "late-scope")) nil)
        (should-not noema-agenda--project-scope)
        (should (equal (car calls) `("leave" (id . "late-scope") (lease . ,lease)))))
      (let ((before (length calls))
            (noema-agenda-project-root-function (lambda (_) (user-error "unsupported placement"))))
        (noema-agenda-activate-project "/fs:unavailable:/project/")
        (should-not noema-agenda--project-root)
        (should (= before (length calls)))))))

(ert-deftest noema-agenda-project-entry-callbacks-share-one-lease-and-cancel-on-exit ()
  (let ((noema-agenda--project-root nil) (noema-agenda--project-scope nil)
        (noema-agenda--project-lease nil) (noema-agenda--project-request 0)
        (noema-agenda--project-callbacks nil) (noema-agenda-project-root-function #'identity)
        calls callbacks results)
    (cl-letf (((symbol-function 'noema-agenda--update-scopes) #'ignore)
              ((symbol-function 'noema-agenda--call)
               (lambda (operation body callback)
                 (push (cons operation body) calls)
                 (when (equal operation "enter") (push callback callbacks)))))
      (noema-agenda-activate-project "/project")
      (noema-agenda-activate-project "/project" (lambda (result error) (push (list result error) results)))
      (should (= (length calls) 1)) (should-not results)
      (funcall (car callbacks) '((id . "scope")) nil)
      (should (equal results '((((id . "scope")) nil))))
      (noema-agenda-activate-project "/next" (lambda (result error) (push (list result error) results)))
      (noema-agenda-activate-project nil)
      (should (equal (alist-get 'message (cadar results)) "Project entry superseded"))
      (should-not noema-agenda--project-callbacks)
      (funcall (car callbacks) '((id . "late-scope")) nil)
      (should (= (length results) 2))
      (should (equal (caar calls) "leave")))))

(ert-deftest noema-agenda-marking-is-local-and-deduplicates-occurrences ()
  (noema-agenda-test--with-buffer
   (setq noema-agenda--blocks '((agenda) (todo)))
   (noema-agenda--render noema-agenda--snapshot)
   (cl-letf (((symbol-function 'noema-agenda--call) (lambda (&rest _) (ert-fail "mark queried sources")))
             ((symbol-function 'org-agenda-format-item) (lambda (&rest _) (ert-fail "mark reformatted entries"))))
     (goto-char (point-min)) (search-forward "Native task")
     (noema-agenda-mark)
     (search-forward "Native task") (noema-agenda-mark)
     (should (equal noema-agenda--marks '("one")))
     (goto-char (point-min)) (search-forward "Native task")
     (should (equal (get-text-property (line-beginning-position) 'display) "* "))
     (noema-agenda-unmark-all)
     (should-not noema-agenda--marks)
     (should-not (buffer-modified-p)))))

(ert-deftest noema-agenda-bulk-keeps-failed-marks-and-uses-one-request ()
  (noema-agenda-test--with-buffer
   (let ((noema-agenda--marks '("one" "two")) request callback)
     (cl-letf (((symbol-function 'noema-agenda--call)
                (lambda (operation body done) (setq request (cons operation body) callback done))))
       (noema-agenda-bulk '((op . "complete")))
       (should (equal (car request) "batch"))
       (should (= (length (alist-get 'items (cdr request))) 2))
       (should (equal (alist-get 'revision (aref (alist-get 'items (cdr request)) 0)) "rev1"))
       (funcall callback '((succeeded . 1) (results . [((uid . "one") (ok . t))
                                                      ((uid . "two") (ok . :json-false) (message . "source changed"))])) nil)
       (should (equal noema-agenda--marks '("two")))))))

(ert-deftest noema-agenda-write-refuses-dirty-source-and-preserves-late-edits ()
  (let ((source (generate-new-buffer " *agenda-source*")) callback reverted)
    (unwind-protect
        (noema-agenda-test--with-buffer
         (cl-letf (((symbol-function 'get-file-buffer) (lambda (_file) source))
                   ((symbol-function 'noema-agenda--call) (lambda (_operation _body done) (setq callback done)))
                   ((symbol-function 'revert-buffer) (lambda (&rest _) (setq reverted t))))
           (with-current-buffer source (insert "unsaved"))
           (goto-char (point-min)) (search-forward "Native task")
           (should-error (noema-agenda-complete) :type 'user-error)
           (should-not callback)
           (with-current-buffer source (set-buffer-modified-p nil))
           (noema-agenda-complete)
           (with-current-buffer source (insert "late edit"))
           (funcall callback '((ok . t)) nil)
           (should-not reverted)
           (should (with-current-buffer source (buffer-modified-p)))))
      (kill-buffer source))))

(ert-deftest noema-agenda-capture-uses-selected-scope-and-inbox ()
  (noema-agenda-test--with-buffer
   (setf (alist-get 'scopes noema-agenda--snapshot)
         [((id . "project:test") (kind . "project") (root . "/project"))])
   (let (request)
     (cl-letf (((symbol-function 'noema-agenda--call)
                (lambda (operation body _callback) (setq request (cons operation body)))))
       (noema-agenda-capture "Follow up" "project:test")
       (should (equal request '("capture" (text . "Follow up") (scopeId . "project:test") (file . "/project/inbox.md"))))
       (should-error (noema-agenda-capture " " "project:test") :type 'user-error)
       (should-error (noema-agenda-capture "Hidden" "inactive") :type 'user-error)))))

(ert-deftest noema-agenda-clock-out-identifies-the-clock-without-a-query ()
  (noema-agenda-test--with-buffer
   (let (request)
     (cl-letf (((symbol-function 'noema-agenda--call)
                (lambda (operation body _callback) (setq request (cons operation body)))))
       (noema-agenda-clock-out '((uid . "clock-one") (scopeId . "project:test") (revision . "clock-rev") (file . "/project/notes.md")))
       (should (equal request '("clock-out" (scopeId . "project:test") (uid . "clock-one") (revision . "clock-rev"))))))))

(ert-deftest noema-agenda-worknode-clock-and-progress-use-native-writer ()
  (noema-agenda-test--with-buffer
   (goto-char (point-min)) (search-forward "Native task")
   (let ((todo (noema-agenda-item-at-point)) request)
     (setf (alist-get 'sourceKind todo) "work-node")
     (cl-letf (((symbol-function 'noema-agenda--call)
                (lambda (operation body _callback) (setq request (cons operation body)))))
       (noema-agenda-clock-in)
       (should (equal request '("clock-in" (scopeId . "knowledge") (uid . "one") (revision . "rev1"))))
       (noema-agenda-progress "37.5")
       (should (equal (alist-get 'patch (cdr request)) '((progress . "37.5"))))
       (should-error (noema-agenda-progress "101") :type 'user-error)))))

(ert-deftest noema-agenda-worknode-clock-metadata-validates-and-copies ()
  (let* ((document (json-parse-string
                    (with-temp-buffer
                      (insert-file-contents (expand-file-name "../poc/org-agenda/example.noema"
                                                              (file-name-directory (locate-library "noema-agenda"))))
                      (buffer-string)) :object-type 'hash-table :array-type 'array))
         (clock (noema-research--table "id" "clock_a" "from" "2026-09-16 09:00"))
         (patch (noema-research--table "progress" "37.5" "clocks" (vector clock))))
    (noema-research-set-agenda document "wn_proof" patch)
    (should-not (plist-get (noema-research-validate document) :errors))
    (should-error (noema-research-set-agenda document "wn_proof" nil) :type 'user-error)
    (puthash "from" "2026-02-30 09:00" clock)
    (should (noema-research-agenda-clock-errors (vector clock)))
    (should-not (plist-get (noema-research-validate document) :errors))
    (should (noema-research-agenda-clock-errors (vector (noema-research--table "id" "b" "from" "2026-09-16")) ))))

(ert-deftest noema-agenda-log-clock-and-project-blocks-use-native-data ()
  (noema-agenda-test--with-buffer
   (let ((snapshot (copy-tree noema-agenda--snapshot)))
     (setf (alist-get 'days snapshot)
           [((date . "2026-09-15") (entries . [((todoId . "two") (kind . "log") (label . "Done"))
                                               ((todoId . "one") (kind . "scheduled") (label . "Scheduled"))]))])
     (setf (alist-get 'clocktable snapshot)
           '((tasks . [((todoId . "one") (text . "Native task") (minutes . 90))])
             (runningClocks . [((text . "Native task") (from . "2026-09-15 10:00") (minutesSoFar . 15))])))
     (setf (alist-get 'projectModel snapshot)
           [((title . "Paper") (done . 1) (total . 2) (progress . 50) (childTodoIds . ["one" "two"]))])
     (setq noema-agenda--snapshot snapshot)
     (cl-letf (((symbol-function 'noema-agenda--call) (lambda (&rest _) (ert-fail "local view made a request"))))
       (noema-agenda-log)
       (should (string-match-p "Finished task" (buffer-string)))
       (should-not (string-match-p "Native task" (buffer-string)))
       (noema-agenda-clocktable)
       (should (string-match-p "1:30" (buffer-string)))
       (should (string-match-p "Running: Native task" (buffer-string)))
       (noema-agenda-projects)
       (should (string-match-p "Paper.*1/2 done" (buffer-string)))
       (should (string-match-p "Native task" (buffer-string)))))))

(ert-deftest noema-agenda-date-picker-returns-native-date-and-prefix-clears ()
  (noema-agenda-test--with-buffer
   (goto-char (point-min)) (search-forward "Native task")
   (let (request)
     (cl-letf (((symbol-function 'org-read-date) (lambda (&rest _) "2026-09-21 09:30"))
               ((symbol-function 'noema-agenda--call) (lambda (_operation body _callback) (setq request body))))
       (call-interactively #'noema-agenda-schedule)
       (should (equal (alist-get 'patch request) '((sche . "2026-09-21 09:30"))))
       (let ((current-prefix-arg '(4))) (call-interactively #'noema-agenda-deadline))
       (should (equal (alist-get 'patch request) '((ddl . ""))))))))

(ert-deftest noema-agenda-date-picker-arrows-control-the-calendar ()
  (let ((map (noema-agenda--date-picker-map)))
    (should (eq (lookup-key map (kbd "<left>")) #'org-calendar-backward-day))
    (should (eq (lookup-key map (kbd "<right>")) #'org-calendar-forward-day))
    (should (eq (lookup-key map (kbd "<up>")) #'org-calendar-backward-week))
    (should (eq (lookup-key map (kbd "<down>")) #'org-calendar-forward-week))
    (should (eq (lookup-key map (kbd "RET")) #'exit-minibuffer))
    (should (eq (lookup-key map (kbd "q")) #'abort-recursive-edit))
    (should (eq (lookup-key map (kbd "<escape>")) #'abort-recursive-edit))))

(ert-deftest noema-agenda-refresh-keeps-the-same-occurrence-of-a-task ()
  (noema-agenda-test--with-buffer
   (let ((snapshot (noema-agenda-test--snapshot)))
     (setf (alist-get 'days snapshot)
           [((date . "2026-09-15") (entries . [((todoId . "one") (kind . "scheduled") (label . "Scheduled"))]))
            ((date . "2026-09-16") (entries . [((todoId . "one") (kind . "deadline") (label . "Deadline"))]))])
     (noema-agenda--render snapshot)
     (goto-char (point-min)) (search-forward "Native task") (search-forward "Native task")
     (noema-agenda--render snapshot)
     (should (equal (get-text-property (point) 'day) (noema-agenda--iso-day "2026-09-16")))
     (should (equal (noema-agenda--get (get-text-property (point) 'noema-agenda-occurrence) 'kind) "deadline")))))

(ert-deftest noema-agenda-calendar-picker-preserves-explicit-time-with-real-org-parser ()
  (noema-agenda-test--with-buffer
   (let ((org-read-date-popup-calendar nil) (current-prefix-arg nil))
     (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "2026-09-21 09:30"))
               ((symbol-function 'org-mode) (lambda (&rest _) (ert-fail "Org source conversion"))))
       (should (equal (noema-agenda--read-date 'sche "Schedule") "2026-09-21 09:30"))))))

(ert-deftest noema-agenda-inactive-clock-stop-does-not-inspect-source-buffers ()
  (noema-agenda-test--with-buffer
   (let (request)
     (cl-letf (((symbol-function 'get-file-buffer) (lambda (&rest _) (ert-fail "inactive source access")))
               ((symbol-function 'noema-agenda--call)
                (lambda (operation body _callback) (setq request (cons operation body)))))
       (noema-agenda-clock-out '((uid . "journal:one") (scopeId . "project:test") (revision . "one")
                                (file . "/inactive/work.noema") (inactive . t)))
       (should (equal (car request) "clock-out"))))))

(ert-deftest noema-agenda-entry-sends-unsaved-source-protection-without-reading-files ()
  (with-temp-buffer
    (setq buffer-file-name "/project/work.noema")
    (insert "unsaved prompt")
    (let (request)
      (cl-letf (((symbol-function 'my/noema--ensure-server) (lambda (callback) (funcall callback)))
                ((symbol-function 'my/noema-api-call)
                 (lambda (_operation args callback &rest _) (setq request (aref args 0)) (funcall callback nil nil)))
                ((symbol-function 'file-exists-p) (lambda (&rest _) (ert-fail "source IO"))))
        (noema-agenda--call "enter" '((root . "/project")) #'ignore)
        (should (member buffer-file-name (append (alist-get 'protectedFiles request) nil)))))))

(ert-deftest noema-agenda-pending-clock-report-and-retry-preserve-deferred-time ()
  (noema-agenda-test--with-buffer
   (setf (alist-get 'clocktable noema-agenda--snapshot)
         '((pendingWrites . [((uid . "journal:one") (text . "Proof") (file . "/project/work.noema")
                               (from . "2026-09-16 09:00") (to . "2026-09-16 10:00") (inactive . t))])))
   (noema-agenda-clocktable)
   (should (string-match-p "waiting for project entry" (buffer-string)))
   (should-error (noema-agenda-clock-retry) :type 'user-error)
   (setf (alist-get 'inactive (aref (alist-get 'pendingWrites (alist-get 'clocktable noema-agenda--snapshot)) 0)) :json-false)
   (let (operation)
     (cl-letf (((symbol-function 'noema-agenda--call) (lambda (op _body _callback) (setq operation op))))
       (noema-agenda-clock-retry)
       (should (equal operation "clock-retry"))))))

(provide 'noema-agenda-tests)

(ert-deftest noema-agenda-navigation-ignores-superseded-and-unfocused-queries ()
  (let ((buffer (generate-new-buffer " *agenda navigation*")) callbacks visited)
    (unwind-protect
        (save-window-excursion
          (switch-to-buffer buffer)
          (cl-letf (((symbol-function 'noema-agenda-item-at-point)
                     (lambda () '((uid . "task") (scopeId . "knowledge"))))
                    ((symbol-function 'noema-agenda--call)
                     (lambda (_op _body callback) (push callback callbacks)))
                    ((symbol-function 'noema-agenda-visit-record)
                     (lambda (record) (push record visited))))
            (noema-agenda-visit)
            (noema-agenda-visit)
            (funcall (cadr callbacks) '((todos . [((uid . "task"))])) nil)
            (should-not visited)
            (funcall (car callbacks) '((todos . [((uid . "task"))])) nil)
            (should (= 1 (length visited)))
            (noema-agenda-visit)
            (switch-to-buffer (get-buffer-create "*scratch*"))
            (funcall (car callbacks) '((todos . [((uid . "task"))])) nil)
            (should (= 1 (length visited)))))
      (kill-buffer buffer))))


(ert-deftest noema-agenda-navigation-resolves-live-task-not-identical-code-text ()
  (let* ((source "@@todo [Same]{id: task}")
         (record `((source . ,source) (sourceRef . ((id . "#task") (revision . "old")))))
         (snapshot `((contentRevision . "new")
                     (todos . [((id . "#task") (index . 73) (source . ,source))]))))
    (should (= 73 (noema-agenda--get (noema-agenda--snapshot-task snapshot record) 'index)))
    (should-error (noema-agenda--snapshot-task '((todos . [])) record) :type 'user-error)))

(ert-deftest noema-agenda-navigation-only-disambiguates-positions-in-the-same-revision ()
  (let ((snapshot '((contentRevision . "v1")
                    (todos . [((index . 0) (source . "@@todo [Same]"))
                               ((index . 14) (source . "@@todo [Same]"))]))))
    (should (= 14 (noema-agenda--get
                   (noema-agenda--snapshot-task snapshot '((source . "@@todo [Same]")
                                                          (sourceRef . ((revision . "v1") (index . 14))))) 'index)))
    (should-error (noema-agenda--snapshot-task snapshot '((source . "@@todo [Same]")
                                                         (sourceRef . ((revision . "v0") (index . 14))))) :type 'user-error)))

(ert-deftest noema-agenda-navigation-verifies-utf16-and-rejects-source-edits ()
  (with-temp-buffer
    (insert "😀\n@@todo [Real]")
    (cl-letf (((symbol-function 'recenter) #'ignore))
      (noema-agenda--goto-snapshot-task '((index . 3) (source . "@@todo [Real]")))
      (should (= (point) 3))
      (should-error (noema-agenda--goto-snapshot-task '((index . 1) (source . "@@todo [Real]"))) :type 'user-error))))

(ert-deftest noema-agenda-navigation-discards-delayed-result-after-edit ()
  (let ((buffer (generate-new-buffer " *agenda source*")) callback visited)
    (unwind-protect
        (save-window-excursion
          (with-current-buffer buffer
            (setq buffer-file-name "/tmp/task.md")
            (insert "@@todo [Real]"))
          (cl-letf (((symbol-function 'find-file-noselect) (lambda (&rest _) buffer))
                    ((symbol-function 'noema-agenda--call)
                     (lambda (op body cb)
                       (should (equal op "document"))
                       (should (equal (alist-get 'content body) "@@todo [Real]"))
                       (setq callback cb)))
                    ((symbol-function 'noema-agenda--goto-snapshot-task) (lambda (_) (setq visited t))))
            (noema-agenda-visit-record '((file . "/tmp/task.md") (source . "@@todo [Real]")))
            (with-current-buffer buffer (insert "Changed "))
            (funcall callback '((todos . [])) nil)
            (should-not visited)))
      (kill-buffer buffer))))
