;;; noema-agenda-attention-tests.el --- Global attention UI contracts -*- lexical-binding: t; -*-
(require 'ert)
(require 'noema-agenda-attention)

(defun noema-attention-test--snapshot ()
  '((revision . 1)
    (items . [((id . "binding") (kind . "reminder") (status . "conflict")
               (active . :false) (ref . ((root . "/fs:lab:/project")))
               (fields . ((title . "手机标题") (completed . t)))
               (sourceCurrent . ((fields . ((title . "源标题") (completed . :false)))))
               (conflicts . ["title" "completed"]))])))

(ert-deftest noema-attention-journal-render-never-opens-or-scans-source ()
  (with-temp-buffer
    (noema-agenda-attention-mode)
    (cl-letf (((symbol-function 'find-file) (lambda (&rest _) (ert-fail "source opened")))
              ((symbol-function 'org-agenda-list) (lambda (&rest _) (ert-fail "Org scan")))
              ((symbol-function 'write-region) (lambda (&rest _) (ert-fail "source written")))
              ((symbol-function 'noema-agenda--call)
               (lambda (operation body callback)
                 (should (equal operation "attention")) (should-not body)
                 (funcall callback (noema-attention-test--snapshot) nil))))
      (noema-agenda-attention-refresh)
      (should (string-match-p "Inactive source" (buffer-string)))
      (should (string-match-p "源标题" (buffer-string)))
      (goto-char (point-min)) (search-forward "手机标题")
      (should (equal (noema-agenda--get (noema-agenda-attention--item) 'id) "binding"))
      (should-not (get-text-property (point) 'org-marker)))))

(ert-deftest noema-attention-hidden-events-defer-and-coalesce-until-visible ()
  (with-temp-buffer
    (noema-agenda-attention-mode)
    (let ((calls 0) callback visible)
      (cl-letf (((symbol-function 'get-buffer-window) (lambda (&rest _) visible))
                ((symbol-function 'noema-agenda--call)
                 (lambda (_operation _body done) (cl-incf calls) (setq callback done))))
        (noema-agenda-attention-refresh)
        (dotimes (_ 20) (noema-agenda-attention-handle-change nil))
        (funcall callback (noema-attention-test--snapshot) nil)
        (should (= calls 1)) (should noema-agenda-attention--dirty)
        (setq visible t) (noema-agenda-attention--visible)
        (should (= calls 2))
        (funcall callback (noema-attention-test--snapshot) nil)
        (should-not noema-agenda-attention--pending)
        (should-not noema-agenda-attention--dirty)))))

(ert-deftest noema-attention-old-response-cannot-overwrite-reopened-buffer ()
  (with-temp-buffer
    (noema-agenda-attention-mode)
    (let (callbacks)
      (cl-letf (((symbol-function 'noema-agenda--call)
                 (lambda (_operation _body done) (push done callbacks))))
        (noema-agenda-attention-refresh)
        (fundamental-mode) (noema-agenda-attention-mode)
        (noema-agenda-attention-refresh)
        (funcall (cadr callbacks) (noema-attention-test--snapshot) nil)
        (should (string-empty-p (buffer-string)))
        (should noema-agenda-attention--pending)
        (funcall (car callbacks) (noema-attention-test--snapshot) nil)
        (should (string-match-p "手机标题" (buffer-string)))))))

(ert-deftest noema-attention-promotion-uses-selected-list-and-nonempty-date-field ()
  (with-temp-buffer
    (noema-agenda-mode)
    (let (request)
      (cl-letf (((symbol-function 'noema-agenda-item-at-point)
                 (lambda () '((uid . "task") (scopeId . "knowledge") (file . "/vault/tasks.md")
                              (sourceRef . ((revision . "revision"))) (canon . ((ddl . "") (sche . "2026-09-18"))))))
                ((symbol-function 'noema-agenda--call)
                 (lambda (operation _body callback)
                   (should (equal operation "attention-collections"))
                   (funcall callback '((timeZone . "floating")
                                       (collections . [((id . "one") (title . "One") (writable . t))
                                                       ((id . "read-only") (title . "No") (writable . :false))
                                                       ((id . "two") (title . "Two") (writable . t))])) nil)))
                ((symbol-function 'completing-read)
                 (lambda (_prompt choices &rest _) (should (= (length choices) 2)) (caadr choices)))
                ((symbol-function 'noema-agenda--write)
                 (lambda (operation body files _callback)
                   (should (equal operation "attention-promote"))
                   (should (equal files '("/vault/tasks.md"))) (setq request body))))
        (noema-agenda-promote "reminder")
        (should (equal (alist-get 'calendarId request) "two"))
        (should (equal (alist-get 'dateField request) "sche"))
        (should (equal (alist-get 'revision request) "revision"))))))

(ert-deftest noema-attention-source-navigation-is-an-explicit-binding-action ()
  (with-temp-buffer
    (noema-agenda-attention-mode)
    (noema-agenda-attention--render (noema-attention-test--snapshot))
    (goto-char (point-min)) (search-forward "手机标题")
    (let (request)
      (cl-letf (((symbol-function 'noema-agenda--call)
                 (lambda (operation body _callback) (setq request (cons operation body)))))
        (noema-agenda-attention-visit)
        (should (equal request '("attention-visit" (id . "binding"))))))))

(provide 'noema-agenda-attention-tests)
