;; C/C++ project using Meson (build dir: ./builddir/)
((nil . ((indent-tabs-mode . nil)
         (tab-width . 4)
         (fill-column . 100)
         (compile-command . "meson compile -C builddir")
         (my/project-local-settings
          . (:task (("setup"  . "meson setup builddir")
                   ("build"  . "meson compile -C builddir")
                   ("test"   . "meson test -C builddir"))
             :run  (("run" . "./builddir/main"))))))
 (c-ts-mode   . ((compile-command . "meson compile -C builddir") (c-basic-offset . 4)))
 (c++-ts-mode . ((compile-command . "meson compile -C builddir") (c-basic-offset . 4)))
 (c-mode      . ((compile-command . "meson compile -C builddir") (c-basic-offset . 4)))
 (c++-mode    . ((compile-command . "meson compile -C builddir") (c-basic-offset . 4))))
