;; Project-wide 4-space indentation (C, Python, Rust style)
((nil . ((indent-tabs-mode . nil)
         (tab-width . 4)
         (fill-column . 88)))
 (python-ts-mode . ((python-indent-offset . 4)))
 (python-mode    . ((python-indent-offset . 4)))
 (c-ts-mode      . ((c-basic-offset . 4)))
 (c++-ts-mode    . ((c-basic-offset . 4)))
 (c-mode         . ((c-basic-offset . 4)))
 (c++-mode       . ((c-basic-offset . 4)))
 (rust-mode      . ((rust-indent-offset . 4)))
 (rust-ts-mode   . ((rust-ts-indent-offset . 4))))
