const PREFIX = "aaronnote:api:research";

const METHODS = Object.freeze({
  "notebook:create": "create",
  "notebook:snapshot": "snapshot",
  "notebook:save": "save",
  "notebook:sync": "sync",
  "notebook:migrate": "migrate",
  "notebook:set-default-agent": "setDefaultAgent",
  "cell:create": "createCell",
  "cell:update": "updateCell",
  "cell:delete": "deleteCell",
  "work-node:delete": "deleteWorkNode",
  "work-node:agenda": "setAgenda",
  "relation:set": "setRelation",
  "state:set": "setState",
  "outputs:clear": "clearOutputs",
  "graph:projection": "projection",
  "events:list": "events",
	"cache:status": "cacheStatus",
	"cache:maintain": "maintainCache",
	"cell:resolve": "resolveCell",
  "capability:list": "capabilities",
  "capability:config": "capabilityConfig",
  "capability:mutate": "mutateCapability",
  "capability:skill:install": "installSkill",
  "capability:skill:prepare": "prepareSkill",
  "capability:probe": "probeMCP",
  "capability:files": "capabilityFiles",
  // New channels prevent pre-global hosts from silently using a project.
  "capability:global:list": "capabilities",
  "capability:global:config": "capabilityConfig",
  "capability:global:mutate": "mutateCapability",
  "capability:global:skill:install": "installSkill",
  "capability:global:probe": "probeMCP",
  "run:prepare": "prepareRun",
  "run:context-preview": "previewRunContext",
	"run:project-file": "runProjectFile",
  "run:list": "runs",
  "run:get": "run",
  "run:cancel": "cancelRun",
  "run:check-completion": "checkRunCompletion",
  "run:fail-preparing": "failPreparingRun",
  "run:live": "liveRun",
	"artifact:read": "readArtifact",
	"artifact:import": "importArtifact",
	"artifact:links": "artifactLinks",
	"corpus:index": "indexArtifactCorpus",
	"corpus:index-files": "indexArtifactFiles",
	"corpus:search": "searchArtifactBlocks",
	"corpus:block-read": "readArtifactBlock",
  "worker:lease": "workerLease",
  "worker:attach": "workerAttach",
  "worker:start": "workerStart",
  "worker:events": "workerEvents",
  "worker:permission": "workerPermission",
	"worker:input": "workerInput",
  "permission:get": "permission",
  "permission:decide": "decidePermission",
	"input:get": "inputRequest",
	"input:respond": "respondInput",
	"attention:list": "attention",
	"proposal:create": "createProposal",
	"supervisor:propose": "supervisorProposal",
	"proposal:get": "proposal",
	"proposal:list": "proposals",
	"proposal:review": "reviewProposal",
	"finding:get": "finding",
	"finding:list": "findings",
	"research-ir:list": "researchIR",
	"problem-model:list": "problemModels",
	"export:create": "exportWorkstream",
	"task:create": "createTask",
	"task:get": "task",
	"task:list": "tasks",
	"task:transition": "transitionTask",
	"job:create": "createJob",
	"job:get": "job",
	"job:list": "jobs",
	"job:claim": "claimJob",
	"job:start": "startJob",
	"job:lease-renew": "renewJobLease",
	"job:lease-expire": "expireJobLeases",
	"job:complete": "completeJob",
	"job:fail": "failJob",
	"job:unresolved": "unresolvedJob",
	"job:retry": "retryJob",
	"invocation:list": "invocations",
	"scheduler-worker:register": "registerSchedulerWorker",
	"scheduler-worker:list": "schedulerWorkers",
	"delegation:create": "createDelegation",
	"delegation:list": "delegations",
	"orchestration:snapshot": "orchestrationSnapshot",
  "session:promote": "promoteSession",
  "session:list": "sessions",
  "session:get": "session",
	"session:context": "sessionContext",
	"session:compact": "compactSession",
	"session:names": "sessionNames",
	"session:name:get": "sessionName",
	"session:name:declare": "declareSessionName",
	"session:name:bind": "bindSessionName",
	"session:name:rename": "renameSessionName",
	"session:name:archive": "archiveSessionName",
	"session:resolve": "resolveSessions",
	"coordinator:claim": "claimCoordinatorRequests",
	"coordinator:complete": "completeCoordinatorRequest",
	"coordinator:endpoint": "coordinatorEndpoint",
	"session:takeover": "takeoverSession",
	"session:handback": "handbackSession",
  "history:index": "indexHistory",
  "history:search": "searchHistory",
  "history:peek": "peekHistory",
  "history:read": "readHistory",
});

export function createResearchApiHandlers(service) {
  return Object.fromEntries(Object.entries(METHODS).map(([channel, method]) => [
    `${PREFIX}:${channel}`,
    async (body) => ({
      type: "research",
      ok: true,
      ...(await service[method]({
        ...(body && typeof body === "object" && !Array.isArray(body) ? body : {}),
        ...(channel.startsWith("capability:global:") ? { scope: "global" } : {}),
      })),
    }),
  ]));
}
