;;; noema-capability-workspace-tests.el --- Scoped editing and Evil -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'noema-capability-ui)

(ert-deftest noema-capability-project-pages-do-not-enumerate-inherited-skills ()
  (with-temp-buffer
    (noema-capability-ui-mode)
    (setq noema-capability-ui--project "/project/" noema-capability-ui--filter "skill")
    (let ((resolution
           '((skills . [((id . "global") (type . "skill") (source . ((scope . "global"))))
                         ((id . "global-patch") (type . "skill") (patches . [((scope . "global"))]))
                         ((id . "project-patch") (type . "skill") (patches . [((scope . "project"))]))
                         ((id . "local") (type . "skill") (source . ((scope . "project"))))]))))
      (setq noema-capability-ui--view 'patches)
      (noema-capability-ui--render resolution)
      (should (equal (mapcar #'car tabulated-list-entries) '(("skill" . "project-patch"))))
      (setq noema-capability-ui--view 'local-skills)
      (noema-capability-ui--render resolution)
      (should (equal (mapcar #'car tabulated-list-entries) '(("skill" . "local"))))
      (setq noema-capability-ui--view 'patches)
      (noema-capability-ui--render '((skills . [((id . "inherited") (type . "skill") (patches . []))])))
      (should-not tabulated-list-entries))))

(ert-deftest noema-capability-evil-keeps-normal-editing-and-safe-command-prefix ()
  (skip-unless (require 'evil nil t))
  (with-temp-buffer
    (evil-local-mode 1)
    (evil-normal-state)
    (let ((baseline (mapcar (lambda (key) (cons key (key-binding (kbd key))))
                           '("j" "k" "h" "l" "d" "f" "i" "u" "/" "1"))))
      (noema-capability-ui-mode)
      (evil-local-mode 1)
      (evil-normal-state)
      (dolist (entry baseline) (should (eq (key-binding (kbd (car entry))) (cdr entry)))))
    (should (eq (key-binding (kbd "C-c p")) #'noema-capability-ui-create-project-patch))
    (should (eq (key-binding (kbd "C-c y")) #'noema-capability-ui-copy-global-skill))
    (should (eq (key-binding (kbd "C-c C-a")) #'noema-capability-ui-menu))
    (should (eq (key-binding (kbd "C-c 2")) #'noema-capability-ui-project-patches))
    (should (eq evil-state 'normal))
    (should evil-local-mode)))

(ert-deftest noema-capability-patch-edit-and-dired-target-project-files ()
  (with-temp-buffer
    (noema-capability-ui-mode)
    (setq noema-capability-ui--project "/project/" noema-capability-ui--view 'patches)
    (noema-capability-ui--render
     '((configFile . "/project/noema-capabilities.json")
       (skills . [((id . "proof") (type . "skill")
                    (source . ((scope . "global") (path . "/global/proof/SKILL.md")))
                    (patches . [((scope . "project") (file . "/project/.agents/skill-patches/proof/skill.patch"))]))])))
    (let (edited browsed)
      (cl-letf (((symbol-function 'noema-capability-ui--open-right)
                 (lambda (file &optional directory _manager)
                   (if directory (setq browsed file) (setq edited file)))))
        (noema-capability-ui-open-source)
        (noema-capability-ui-open-directory))
      (should (equal edited "/project/.agents/skill-patches/proof/skill.patch"))
      (should (equal browsed "/project/.agents/skill-patches/proof/")))))

(ert-deftest noema-capability-global-buttons-create-project-workspaces-not-global-mutations ()
  (with-temp-buffer
    (noema-capability-ui-mode)
    (setq noema-capability-ui--project "/project/")
    (noema-capability-ui--render '((skills . [((id . "proof") (type . "skill"))])))
    (let (calls)
      (cl-letf (((symbol-function 'noema-skill-prepare) (lambda (&rest args) (push args calls))))
        (noema-capability-ui-create-project-patch)
        (noema-capability-ui-copy-global-skill))
      (should (equal (mapcar (lambda (args) (seq-take args 2)) (reverse calls)) '(("proof" "patch") ("proof" "copy"))))
      (dolist (args calls) (should (equal (plist-get (cddr args) :project) "/project/"))))))

(ert-deftest noema-capability-empty-local-page-can-choose-a-global-skill ()
  (with-temp-buffer
    (noema-capability-ui-mode)
    (setq noema-capability-ui--project "/project/" noema-capability-ui--view 'local-skills)
    (let (called)
      (cl-letf (((symbol-function 'noema-skill-list)
                 (lambda (&rest args)
                   (should (eq (plist-get args :scope) 'global))
                   (funcall (plist-get args :callback) '(((id . "proof"))) nil)))
                ((symbol-function 'completing-read) (lambda (&rest _) "proof"))
                ((symbol-function 'noema-skill-prepare) (lambda (&rest args) (setq called args))))
        (noema-capability-ui-copy-global-skill))
      (should (equal (seq-take called 2) '("proof" "copy"))))))

(ert-deftest noema-capability-agent-refinement-is-a-reviewable-draft ()
  (require 'noema-agent-acp)
  (with-temp-buffer
    (noema-capability-ui-mode)
    (setq noema-capability-ui--project "/project/" noema-capability-ui--view 'patches)
    (noema-capability-ui--render
     '((skills . [((id . "proof") (type . "skill") (source . ((path . "/global/proof/SKILL.md")))
                    (patches . [((scope . "project") (file . "/project/.agents/skill-patches/proof/skill.patch"))]))])))
    (let (draft)
      (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "codex"))
                ((symbol-function 'read-string) (lambda (&rest _) "Make the proof checks stricter"))
                ((symbol-function 'noema-agent-acp-config-for) #'identity)
                ((symbol-function 'noema-agent-acp-start) (lambda (&rest _) (current-buffer)))
                ((symbol-function 'noema-agent-acp-draft) (lambda (_buffer text) (setq draft text)))
                ((symbol-function 'noema-agent-acp-prompt) (lambda (&rest _) (ert-fail "Auto-submitted draft"))))
        (noema-capability-ui-edit-with-agent))
      (should (string-match-p (regexp-quote "/project/.agents/skill-patches/proof/skill.patch") draft))
      (should (string-match-p "Do not modify global Skills" draft)))))

(ert-deftest noema-capability-files-open-right-and-leave-manager-visible ()
  (save-window-excursion
    (let ((manager (generate-new-buffer " *noema-manager-window-test*"))
          (file (make-temp-file "noema-manager-window-" nil ".md"))
          edited)
      (unwind-protect
          (progn
            (delete-other-windows)
            (switch-to-buffer manager)
            (noema-capability-ui-mode)
            (let ((left (selected-window)))
              (setq edited (noema-capability-ui--open-right file))
              (should (eq (window-buffer left) manager))
              (should (> (car (window-edges (selected-window))) (car (window-edges left))))
              (should (eq (window-buffer (selected-window)) edited))
              (select-window left)
              (noema-capability-ui--open-right file)
              (should (= 2 (length (window-list))))))
        (when (buffer-live-p edited) (kill-buffer edited))
        (kill-buffer manager)
        (delete-file file)))))

(provide 'noema-capability-workspace-tests)
