;;; noema-findings-tests.el --- Evidence board checks -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'noema-findings)
(require 'noema-research-inspector)
(require 'noema-research-synthesis)

(ert-deftest noema-findings-project-query-and-evidence ()
  "The board requests local project claims and retains evidence metadata."
  (with-temp-buffer
    (noema-findings-mode)
    (setq noema-findings--root "/tmp/noema-findings-test/"
          noema-findings--query "signal")
    (let (body callback)
      (cl-letf (((symbol-function 'my/noema-api-call)
                 (lambda (channel args done &optional _timeout)
                   (should (equal channel "aaronnote:api:research:finding:list"))
                   (setq body (aref args 0) callback done))))
        (noema-findings-refresh)
        (should (equal (alist-get 'cwd body) "/tmp/noema-findings-test/"))
        (should (equal (alist-get 'query body) "signal"))
        (should (eq (alist-get 'includeLocal body) t))
        (funcall callback
                 '((findings . [((id . "finding-1") (kind . "claim")
                                (statement . "A signal exists")
                                (verificationLevel . "agent_checked")
                                (evidence . [((artifactId . "artifact-1")
                                              (relation . "supports"))]))])) nil)
        (should (= 1 (length noema-findings--records)))
        (should (equal (aref (cadr (car tabulated-list-entries)) 3) "1"))))))

(ert-deftest noema-run-memory-review-requires-evidence-confirmation ()
  "A Handoff memory enters recall only after a person checks its evidence."
  (let* ((finding (make-hash-table :test 'equal))
         (verification (make-hash-table :test 'equal))
         (payload (make-hash-table :test 'equal))
         (proposal (make-hash-table :test 'equal)))
    (puthash "statement" "Use SQLite" finding)
    (puthash "status" "proposed" finding)
    (puthash "level" "unreviewed" verification)
    (puthash "verification" verification finding)
    (puthash "finding" finding payload)
    (puthash "payload" payload proposal)
    (puthash "sourceAdapter" "noema-run-handoff" proposal)
    (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) nil)))
      (should-error (noema-research-attention--run-memory-review proposal) :type 'user-error))
    (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
      (let* ((edited (noema-research-attention--run-memory-review proposal))
             (reviewed (gethash "finding" edited)))
        (should (equal (gethash "status" reviewed) "supported"))
        (should (equal (gethash "level" (gethash "verification" reviewed)) "human_reviewed"))
        (should (equal (gethash "status" finding) "proposed"))))))

(ert-deftest noema-run-memory-command-submits-pending-proposal ()
  "The command submits an exact excerpt and never accepts it itself."
  (let (request)
    (cl-letf (((symbol-function 'noema-current-project) (lambda (&optional _) "/tmp/project/"))
              ((symbol-function 'my/noema-api-call)
               (lambda (channel args callback &optional _timeout)
                 (should (equal channel "aaronnote:api:research:memory:propose-from-run"))
                 (setq request (aref args 0))
                 (let ((proposal (make-hash-table :test 'equal))
                       (response (make-hash-table :test 'equal)))
                   (puthash "id" "prop_1" proposal)
                   (puthash "status" "pending" proposal)
                   (puthash "proposal" proposal response)
                   (funcall callback response nil)))))
      (noema-research-propose-memory-from-run "run_1" "decision" "Use SQLite" "project")
      (should (equal (alist-get 'runId request) "run_1"))
      (should (equal (alist-get 'statement request) "Use SQLite")))))

(ert-deftest noema-findings-retire-sends-version-and-reason ()
  "Retiring asks for confirmation and sends the listed version."
  (with-temp-buffer
    (noema-findings-mode)
    (setq noema-findings--root "/tmp/noema-findings-test/")
    (noema-findings--render [((id . "finding_1") (kind . "claim") (status . "supported")
                              (statement . "A signal exists") (version . 3)
                              (verificationLevel . "human_reviewed") (evidence . []))])
    (goto-char (point-min))
    ;; `yes-or-no-p' is a primitive; replacing it must not depend on a
    ;; native-compilation trampoline being buildable in the test process.
    (let ((native-comp-enable-subr-trampolines nil)
          channels body)
      (cl-letf (((symbol-function 'my/noema-api-call)
                 (lambda (channel args done &optional _timeout)
                   (push channel channels)
                   (when (equal channel "aaronnote:api:research:finding:retire")
                     (setq body (aref args 0))
                     (funcall done '((finding . ((id . "finding_1")))) nil))))
                ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
        (should-error (noema-findings-retire "refuted" "  ") :type 'user-error)
        (noema-findings-retire "refuted" " mislabelled benchmark ")
        (should (equal (alist-get 'id body) "finding_1"))
        (should (equal (alist-get 'status body) "refuted"))
        (should (equal (alist-get 'reason body) "mislabelled benchmark"))
        (should (equal (alist-get 'expectedVersion body) 3))
        ;; The list reloads after the kernel confirms.
        (should (equal (car channels) "aaronnote:api:research:finding:list"))))))

(provide 'noema-findings-tests)
;;; noema-findings-tests.el ends here
