;;; noema-agent-inbox-tests.el --- Global agent inbox checks -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'noema-agent-inbox)

(ert-deftest noema-agent-inbox-discovers-only-research-projects ()
  "A Wiki manifest and disposable worktree must not become inbox Projects."
  (let* ((root (make-temp-file "noema-inbox-" t))
         (wiki (expand-file-name "public/AI" root))
         (project (expand-file-name "private/research/study" root))
         (worktree (expand-file-name ".noema/worktrees/disposable" root)))
    (unwind-protect
        (progn
          (dolist (dir (list wiki project worktree)) (make-directory dir t))
          (with-temp-file (expand-file-name "noema.toml" wiki)
            (insert "repository_id = \"wiki\"\n"))
          (with-temp-file (expand-file-name "noema.toml" project)
            (insert "[project]\nid = \"study\"\n"))
          (with-temp-file (expand-file-name "noema.toml" worktree)
            (insert "[project]\nid = \"disposable\"\n"))
          (cl-letf (((symbol-function 'noema-agent-inbox--note-root)
                     (lambda () (file-name-as-directory root))))
            (should (equal (noema-agent-inbox--note-projects)
                           (list (file-name-as-directory project))))))
      (delete-directory root t))))

(ert-deftest noema-agent-inbox-ignores-stale-project-responses ()
  "An older refresh cannot replace a newer Session result."
  (with-temp-buffer
    (noema-agent-inbox-mode)
    (let ((root "/tmp/noema-inbox-project/") callbacks)
      (setq noema-agent-inbox--roots (list root))
      (cl-letf (((symbol-function 'noema-sessions--api)
                 (lambda (_channel _body callback) (push callback callbacks)))
                ((symbol-function 'noema-agent-acp-sessions) (lambda (&optional _root) nil)))
        (noema-agent-inbox-refresh)
        (let ((old (car callbacks)))
          (noema-agent-inbox-refresh)
          (funcall (car callbacks)
                   '((names . [((name . "current") (agent . "codex"))])) nil)
          (funcall old '((names . [((name . "stale") (agent . "claude"))])) nil)
          (should (string-match-p "current" (buffer-string)))
          (should-not (string-match-p "stale" (buffer-string))))))))

(ert-deftest noema-agent-inbox-shows-failed-project-and-deduplicates-live-session ()
  "A failed query remains visible; a promoted live buffer has one row."
  (let ((agent (generate-new-buffer " *noema-inbox-agent*")))
    (unwind-protect
        (with-temp-buffer
          (noema-agent-inbox-mode)
          (let* ((root "/tmp/noema-inbox-project/")
                 (failed "/tmp/noema-inbox-failed/")
                 (entry '((name . "reviewer") (sessionId . "sid-1")
                          (agent . "codex") (attentionReason . "permission")))
                 (noema-agent-inbox--roots (list root failed))
                 (noema-agent-inbox--results (make-hash-table :test #'equal)))
            (puthash root `((names . [,entry])) noema-agent-inbox--results)
            (puthash failed '(:error ((message . "host unavailable")))
                     noema-agent-inbox--results)
            (cl-letf (((symbol-function 'noema-sessions--live-buffer)
                       (lambda (_entry _root) agent))
                      ((symbol-function 'noema-agent-acp-busy-p)
                       (lambda (_buffer) nil))
                      ((symbol-function 'noema-agent-acp-sessions)
                       (lambda (&optional _root)
                         (list (list :buffer agent :root root :name "reviewer"
                                     :agent "codex")))))
              (noema-agent-inbox--render)
              (should (= (length tabulated-list-entries) 2))
              (should (string-match-p "!approve" (buffer-string)))
              (should (string-match-p "host unavailable" (buffer-string)))
              (should-not (string-match-p "reviewer.*reviewer" (buffer-string))))))
      (kill-buffer agent))))

(ert-deftest noema-agent-inbox-opens-duplicate-names-by-project-and-session-id ()
  "The same Session name in two Projects must route to the selected identity."
  (with-temp-buffer
    (noema-agent-inbox-mode)
    (let* ((first "/tmp/inbox-first/")
           (second "/tmp/inbox-second/")
           (noema-agent-inbox--roots (list first second))
           (noema-agent-inbox--results (make-hash-table :test #'equal))
           opened jumped)
      (puthash first '((names . [((name . "reviewer") (sessionId . "sid-a"))]))
               noema-agent-inbox--results)
      (puthash second '((names . [((name . "reviewer") (sessionId . "sid-b")
                                   (lastRun . ((notebookId . "nb-b") (cellId . "cell-b"))))]))
               noema-agent-inbox--results)
      (cl-letf (((symbol-function 'noema-agent-acp-sessions) (lambda (&optional _root) nil))
                ((symbol-function 'noema-sessions-open-reference)
                 (lambda (root name id) (setq opened (list root name id))))
                ((symbol-function 'noema-sessions--jump-to-run)
                 (lambda (root name run)
                   (setq jumped (list root name (noema-sessions--string run "cellId")))))
                ((symbol-function 'noema-sessions--note-read)
                 (lambda (_entry _root) nil)))
        (noema-agent-inbox--render)
        (goto-char (point-min))
        (search-forward "inbox-second")
        (beginning-of-line)
        (noema-agent-inbox-visit)
        (should (equal opened (list second "reviewer" "sid-b")))
        (noema-agent-inbox-jump)
        (should (equal jumped (list second "reviewer" "cell-b")))))))

(provide 'noema-agent-inbox-tests)
;;; noema-agent-inbox-tests.el ends here
