;;; noema-capability-workspace-tests.el --- Scoped editing and Evil -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'noema-capability-ui)

(ert-deftest noema-capability-project-pages-do-not-enumerate-inherited-skills ()
  (with-temp-buffer
    (noema-capability-ui-mode)
    (setq noema-capability-ui--project "/project/" noema-capability-ui--filter "skill")
    (let ((resolution
           '((skills . [((id . "global") (type . "skill") (source . ((scope . "global"))))
                         ((id . "global-patch") (type . "skill") (patches . [((scope . "global"))]))
                         ((id . "project-patch") (type . "skill") (patches . [((scope . "project"))]))
                         ((id . "local") (type . "skill") (source . ((scope . "project"))))]))))
      (setq noema-capability-ui--view 'patches)
      (noema-capability-ui--render resolution)
      (should (equal (mapcar #'car tabulated-list-entries) '(("skill" . "project-patch"))))
      (setq noema-capability-ui--view 'local-skills)
      (noema-capability-ui--render resolution)
      (should (equal (mapcar #'car tabulated-list-entries) '(("skill" . "local"))))
      (setq noema-capability-ui--view 'patches)
      (noema-capability-ui--render '((skills . [((id . "inherited") (type . "skill") (patches . []))])))
      (should-not tabulated-list-entries))))

(ert-deftest noema-capability-unavailable-skill-is-a-warning-not-an-error-label ()
  (let ((record '((id . "plugin-skill") (type . "skill")
                  (validation . ((valid . :false) (errors . []) (warnings . [])))
                  (diagnostics . [((severity . "warning")
                                   (code . "unavailable-skill"))]))))
    (should (equal (substring-no-properties
                    (noema-capability-ui--validation record))
                   "unavailable"))))

(ert-deftest noema-capability-evil-keeps-normal-editing-and-safe-command-prefix ()
  (skip-unless (require 'evil nil t))
  (with-temp-buffer
    (evil-local-mode 1)
    (evil-normal-state)
    (let ((baseline (mapcar (lambda (key) (cons key (key-binding (kbd key))))
                           '("j" "k" "h" "l" "d" "f" "i" "u" "/" "1"))))
      (noema-capability-ui-mode)
      (evil-local-mode 1)
      (evil-normal-state)
      (dolist (entry baseline) (should (eq (key-binding (kbd (car entry))) (cdr entry)))))
    (should (eq (key-binding (kbd "C-c p")) #'noema-capability-ui-create-project-patch))
    (should (eq (key-binding (kbd "C-c y")) #'noema-capability-ui-copy-global-skill))
    (should (eq (key-binding (kbd "C-c C-a")) #'noema-capability-ui-menu))
    (should (eq (key-binding (kbd "C-c 2")) #'noema-capability-ui-project-patches))
    (should (eq evil-state 'normal))
    (should evil-local-mode)))

(ert-deftest noema-capability-patch-edit-and-dired-target-project-files ()
  (with-temp-buffer
    (noema-capability-ui-mode)
    (setq noema-capability-ui--project "/project/" noema-capability-ui--view 'patches)
    (noema-capability-ui--render
     '((configFile . "/project/noema-capabilities.json")
       (skills . [((id . "proof") (type . "skill")
                    (source . ((scope . "global") (path . "/global/proof/SKILL.md")))
                    (patches . [((scope . "project") (file . "/project/.agents/skill-patches/proof/skill.patch"))]))])))
    (let (edited browsed)
      (cl-letf (((symbol-function 'noema-capability-ui--open-right)
                 (lambda (file &optional directory _manager)
                   (if directory (setq browsed file) (setq edited file)))))
        (noema-capability-ui-open-source)
        (noema-capability-ui-open-directory))
      (should (equal edited "/project/.agents/skill-patches/proof/skill.patch"))
      (should (equal browsed "/project/.agents/skill-patches/proof/")))))

(ert-deftest noema-capability-global-buttons-create-project-workspaces-not-global-mutations ()
  (with-temp-buffer
    (noema-capability-ui-mode)
    (setq noema-capability-ui--project "/project/")
    (noema-capability-ui--render '((skills . [((id . "proof") (type . "skill"))])))
    (let (calls)
      (cl-letf (((symbol-function 'noema-skill-prepare) (lambda (&rest args) (push args calls))))
        (noema-capability-ui-create-project-patch)
        (noema-capability-ui-copy-global-skill))
      (should (equal (mapcar (lambda (args) (seq-take args 2)) (reverse calls)) '(("proof" "patch") ("proof" "copy"))))
      (dolist (args calls) (should (equal (plist-get (cddr args) :project) "/project/"))))))

(ert-deftest noema-capability-empty-local-page-can-choose-a-global-skill ()
  (with-temp-buffer
    (noema-capability-ui-mode)
    (setq noema-capability-ui--project "/project/" noema-capability-ui--view 'local-skills)
    (let (called)
      (cl-letf (((symbol-function 'noema-skill-list)
                 (lambda (&rest args)
                   (should (eq (plist-get args :scope) 'global))
                   (funcall (plist-get args :callback) '(((id . "proof"))) nil)))
                ((symbol-function 'completing-read) (lambda (&rest _) "proof"))
                ((symbol-function 'noema-skill-prepare) (lambda (&rest args) (setq called args))))
        (noema-capability-ui-copy-global-skill))
      (should (equal (seq-take called 2) '("proof" "copy"))))))

(ert-deftest noema-capability-agent-refinement-is-a-reviewable-draft ()
  (require 'noema-agent-acp)
  (with-temp-buffer
    (noema-capability-ui-mode)
    (setq noema-capability-ui--project "/project/" noema-capability-ui--view 'patches)
    (noema-capability-ui--render
     '((skills . [((id . "proof") (type . "skill") (source . ((path . "/global/proof/SKILL.md")))
                    (patches . [((scope . "project") (file . "/project/.agents/skill-patches/proof/skill.patch"))]))])))
    (let (draft)
      (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "codex"))
                ((symbol-function 'read-string) (lambda (&rest _) "Make the proof checks stricter"))
                ((symbol-function 'noema-agent-acp-config-for) #'identity)
                ((symbol-function 'noema-agent-acp-start) (lambda (&rest _) (current-buffer)))
                ((symbol-function 'noema-agent-acp-draft) (lambda (_buffer text) (setq draft text)))
                ((symbol-function 'noema-agent-acp-prompt) (lambda (&rest _) (ert-fail "Auto-submitted draft"))))
        (noema-capability-ui-edit-with-agent))
      (should (string-match-p (regexp-quote "/project/.agents/skill-patches/proof/skill.patch") draft))
      (should (string-match-p "Do not modify global Skills" draft)))))

(ert-deftest noema-capability-files-open-right-and-leave-manager-visible ()
  (save-window-excursion
    (let ((manager (generate-new-buffer " *noema-manager-window-test*"))
          (file (make-temp-file "noema-manager-window-" nil ".md"))
          edited)
      (unwind-protect
          (progn
            (delete-other-windows)
            (switch-to-buffer manager)
            (noema-capability-ui-mode)
            (let ((left (selected-window)))
              (setq edited (noema-capability-ui--open-right file))
              (should (eq (window-buffer left) manager))
              (should (> (car (window-edges (selected-window))) (car (window-edges left))))
              (should (eq (window-buffer (selected-window)) edited))
              (select-window left)
              (noema-capability-ui--open-right file)
              (should (= 2 (length (window-list))))))
        (when (buffer-live-p edited) (kill-buffer edited))
        (kill-buffer manager)
        (delete-file file)))))

(provide 'noema-capability-workspace-tests)

(defconst noema-capability-test--pack-resolution
  '((skills . [((id . "proof-plan") (type . "skill") (enabled . :false) (selectable . t)
                (source . ((scope . "global") (path . "skills/proof-plan/SKILL.md"))))
               ((id . "lean4") (type . "skill") (enabled . :false) (selectable . t)
                (source . ((scope . "global"))))])
    (packs . [((id . "math-verification") (type . "pack") (enabled . :false) (selectable . t)
               (source . ((scope . "global") (path . "capabilities.json")))
               (members . [((id . "proof-plan") (state . "available"))
                           ((id . "lean4") (state . "available"))]))
              ((id . "quantum") (type . "pack") (enabled . :false) (selectable . :false)
               (source . ((scope . "global")))
               (patches . [((scope . "project"))])
               (members . [((id . "qiskit") (state . "missing"))]))])))

(ert-deftest noema-capability-packs-page-expands-member-links ()
  (with-temp-buffer
    (noema-capability-ui-mode)
    (setq noema-capability-ui--view 'packs noema-capability-ui--filter "pack"
          tabulated-list-sort-key nil)
    (noema-capability-ui--render noema-capability-test--pack-resolution)
    (should (equal (mapcar #'car tabulated-list-entries)
                   '(("pack" . "math-verification") ("pack" . "quantum"))))
    (should (equal (aref (cadr (car tabulated-list-entries)) 7) "2 skills"))
    (goto-char (point-min))
    (while (not (equal (tabulated-list-get-id) '("pack" . "math-verification"))) (forward-line 1))
    (noema-capability-ui-visit)
    (should (equal (mapcar #'car tabulated-list-entries)
                   '(("pack" . "math-verification")
                     (member "math-verification" "proof-plan")
                     (member "math-verification" "lean4")
                     ("pack" . "quantum"))))
    ;; A member row acts on the ordinary flat Skill record.
    (forward-line 1)
    (should (equal (tabulated-list-get-id) '(member "math-verification" "proof-plan")))
    (should (equal (noema--value (noema-capability-ui--record-at-point) "type") "skill"))
    (should (equal (noema--value (noema-capability-ui--record-at-point) "id") "proof-plan"))
    (forward-line -1)
    (noema-capability-ui-visit)
    (should (= (length tabulated-list-entries) 2))))

(ert-deftest noema-capability-project-patch-page-lists-patched-packs-for-skill-managers ()
  (with-temp-buffer
    (noema-capability-ui-mode)
    (setq noema-capability-ui--project "/project/" noema-capability-ui--filter "skill"
          noema-capability-ui--view 'patches)
    (noema-capability-ui--render noema-capability-test--pack-resolution)
    (should (equal (mapcar #'car tabulated-list-entries) '(("pack" . "quantum"))))))

(ert-deftest noema-capability-packs-page-is-global-and-keyed ()
  (with-temp-buffer
    (noema-capability-ui-mode)
    (setq noema-capability-ui--view 'packs)
    (should (eq (noema-capability-ui--scope) 'global))
    (should (equal (noema-capability-ui--scope-label) "Packs · etc/noema"))
    (should (eq (key-binding (kbd "C-c 4")) #'noema-capability-ui-packs))
    (should (eq (key-binding (kbd "C-c U")) #'noema-skill-upstream))
    (should (eq (key-binding (kbd "RET")) #'noema-capability-ui-visit))))

(ert-deftest noema-capability-pack-project-patch-writes-membership-delta ()
  (with-temp-buffer
    (noema-capability-ui-mode)
    (setq noema-capability-ui--project "/project/" noema-capability-ui--view 'packs
          noema-capability-ui--resolution noema-capability-test--pack-resolution)
    (let (written answers)
      (setq answers (list '("lean4") '("qiskit")))
      (cl-letf (((symbol-function 'noema-capability-config)
                 (lambda (&rest args)
                   (should (equal (plist-get args :project) "/project/"))
                   (funcall (plist-get args :callback) '((config . ((packs . ((patches . nil)))))) nil)))
                ((symbol-function 'completing-read-multiple) (lambda (&rest _) (pop answers)))
                ((symbol-function 'read-string) (lambda (&rest _) "Prefer Qiskit."))
                ((symbol-function 'noema-capability-set-patch)
                 (lambda (type id patch &rest args)
                   (setq written (list type id patch (plist-get args :scope))))))
        (noema-capability-ui--pack-project-patch
         (seq-find (lambda (r) (equal (noema--value r "id") "math-verification"))
                   (noema--sequence (noema--value noema-capability-test--pack-resolution "packs")))))
      (should (equal written '("pack" "math-verification"
                               ((members_remove . ["lean4"]) (members_add . ["qiskit"])
                                (preamble_append . "Prefer Qiskit."))
                               project))))))

(ert-deftest noema-skill-upstream-view-renders-lock-state-and-uses-global-channels ()
  (require 'noema-skill-upstream-ui)
  (with-temp-buffer
    (noema-skill-upstream-mode)
    (noema-skill-upstream--render
     '((lockFile . "/etc/noema/skills.lock.json") (checked . t)
       (skills . [((id . "qiskit") (local . "clean") (commit . "0123456789abcdef0123")
                   (latest . "fedcba9876543210fedc") (updateAvailable . t) (ref . "HEAD")
                   (repository . "K-Dense-AI/claude-scientific-skills") (path . "skills/qiskit")
                   (history . []))
                  ((id . "math-prose") (local . "modified") (commit . "71ece05af05a") (ref . "HEAD")
                   (repository . "TianhuaGao/math-prose") (path . ".") (history . [((commit . "aa"))]))])))
    (should (equal (sort (mapcar #'car tabulated-list-entries) #'string<) '("math-prose" "qiskit")))
    (let ((row (cadr (assoc "qiskit" tabulated-list-entries))))
      (should (equal (substring-no-properties (aref row 3)) "fedcba987654"))
      (should (equal (aref row 2) "0123456789ab")))
    (should (string-match-p "1 updates · 1 edited locally" (car header-line-format)))
    (should (eq (key-binding (kbd "C-c u")) #'noema-skill-upstream-ui-update)))
  (let ((my/noema--ready t) calls)
    (cl-letf (((symbol-function 'noema--host-call-now)
               (lambda (channel body _callback &optional timeout) (push (list channel body timeout) calls))))
      (noema-skill-upstream-status :check t :callback #'ignore)
      (noema-skill-upstream-update "qiskit" :dry-run t :callback #'ignore))
    (should (equal (mapcar #'car calls)
                   '("aaronnote:api:research:capability:global:skill:upstream:update"
                     "aaronnote:api:research:capability:global:skill:upstream:status")))
    (should (equal (mapcar #'caddr calls) (list noema-skill-upstream-timeout noema-skill-upstream-timeout)))))

(ert-deftest noema-capability-gateway-json-false-renders-disabled ()
  "The remote gateway decodes JSON false as `:json-false'."
  (should-not (noema-capability-ui--truth-p :json-false))
  (let ((entry (noema-capability-ui--entry
                '((id . "p") (type . "pack") (enabled . :json-false)
                  (validation . ((valid . :json-false) (errors . []) (warnings . [])))
                  (members . [])))))
    (should (equal (substring-no-properties (aref (cadr entry) 2)) "no"))
    (should (equal (substring-no-properties (aref (cadr entry) 6)) "error"))))
