;;; noema-agent-inbox-tests.el --- Global agent inbox checks -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'noema-agent-inbox)
(require 'noema-agent-worker)

(ert-deftest noema-agent-inbox-discovers-only-research-projects ()
  "A Wiki manifest and disposable worktree must not become inbox Projects."
  (let* ((root (make-temp-file "noema-inbox-" t))
         (wiki (expand-file-name "public/AI" root))
         (project (expand-file-name "private/research/study" root))
         (worktree (expand-file-name ".noema/worktrees/disposable" root)))
    (unwind-protect
        (progn
          (dolist (dir (list wiki project worktree)) (make-directory dir t))
          (with-temp-file (expand-file-name "noema.toml" wiki)
            (insert "repository_id = \"wiki\"\n"))
          (with-temp-file (expand-file-name "noema.toml" project)
            (insert "[project]\nid = \"study\"\n"))
          (with-temp-file (expand-file-name "noema.toml" worktree)
            (insert "[project]\nid = \"disposable\"\n"))
          (cl-letf (((symbol-function 'noema-agent-inbox--note-root)
                     (lambda () (file-name-as-directory root))))
            (should (equal (noema-agent-inbox--note-projects)
                           (list (file-name-as-directory project))))))
      (delete-directory root t))))

(ert-deftest noema-agent-inbox-ignores-stale-project-responses ()
  "An older refresh cannot replace a newer Session result."
  (with-temp-buffer
    (noema-agent-inbox-mode)
    (let ((root "/tmp/noema-inbox-project/") callbacks)
      (setq noema-agent-inbox--roots (list root))
      (cl-letf (((symbol-function 'noema-sessions--api)
                 (lambda (_channel _body callback) (push callback callbacks)))
                ((symbol-function 'noema-agent-acp-sessions) (lambda (&optional _root) nil)))
        (noema-agent-inbox-refresh)
        (let ((old (car callbacks)))
          (noema-agent-inbox-refresh)
          (funcall (car callbacks)
                   '((names . [((name . "current") (agent . "codex"))])) nil)
          (funcall old '((names . [((name . "stale") (agent . "claude"))])) nil)
          (should (string-match-p "current" (buffer-string)))
          (should-not (string-match-p "stale" (buffer-string))))))))

(ert-deftest noema-agent-inbox-shows-failed-project-and-deduplicates-live-session ()
  "A failed query remains visible; a promoted live buffer has one row."
  (let ((agent (generate-new-buffer " *noema-inbox-agent*")))
    (unwind-protect
        (with-temp-buffer
          (noema-agent-inbox-mode)
          (let* ((root "/tmp/noema-inbox-project/")
                 (failed "/tmp/noema-inbox-failed/")
                 (entry '((name . "reviewer") (sessionId . "sid-1")
                          (agent . "codex") (attentionReason . "permission")))
                 (noema-agent-inbox--roots (list root failed))
                 (noema-agent-inbox--results (make-hash-table :test #'equal)))
            (puthash root `((names . [,entry])) noema-agent-inbox--results)
            (puthash failed '(:error ((message . "host unavailable")))
                     noema-agent-inbox--results)
            (cl-letf (((symbol-function 'noema-sessions--live-buffer)
                       (lambda (_entry _root) agent))
                      ((symbol-function 'noema-agent-acp-busy-p)
                       (lambda (_buffer) nil))
                      ((symbol-function 'noema-agent-acp-sessions)
                       (lambda (&optional _root)
                         (list (list :buffer agent :root root :name "reviewer"
                                     :agent "codex")))))
              (noema-agent-inbox--render)
              (should (= (length tabulated-list-entries) 2))
              (should (string-match-p "!approve" (buffer-string)))
              (should (string-match-p "host unavailable" (buffer-string)))
              (should-not (string-match-p "reviewer.*reviewer" (buffer-string))))))
      (kill-buffer agent))))

(ert-deftest noema-agent-inbox-opens-duplicate-names-by-project-and-session-id ()
  "The same Session name in two Projects must route to the selected identity."
  (with-temp-buffer
    (noema-agent-inbox-mode)
    (let* ((first "/tmp/inbox-first/")
           (second "/tmp/inbox-second/")
           (noema-agent-inbox--roots (list first second))
           (noema-agent-inbox--results (make-hash-table :test #'equal))
           opened jumped)
      (puthash first '((names . [((name . "reviewer") (sessionId . "sid-a"))]))
               noema-agent-inbox--results)
      (puthash second '((names . [((name . "reviewer") (sessionId . "sid-b")
                                   (lastRun . ((notebookId . "nb-b") (cellId . "cell-b"))))]))
               noema-agent-inbox--results)
      (cl-letf (((symbol-function 'noema-agent-acp-sessions) (lambda (&optional _root) nil))
                ((symbol-function 'noema-sessions-open-reference)
                 (lambda (root name id) (setq opened (list root name id))))
                ((symbol-function 'noema-sessions--jump-to-run)
                 (lambda (root name run)
                   (setq jumped (list root name (noema-sessions--string run "cellId")))))
                ((symbol-function 'noema-sessions--note-read)
                 (lambda (_entry _root) nil)))
        (noema-agent-inbox--render)
        (goto-char (point-min))
        (search-forward "inbox-second")
        (beginning-of-line)
        (noema-agent-inbox-visit)
        (should (equal opened (list second "reviewer" "sid-b")))
        (noema-agent-inbox-jump)
        (should (equal jumped (list second "reviewer" "cell-b")))))))

(ert-deftest noema-agent-inbox-cycles-attention-and-reads-selected-project ()
  "Global attention navigation skips quiet rows and keeps Project identity."
  (with-temp-buffer
    (noema-agent-inbox-mode)
    (let* ((first "/tmp/inbox-first/")
           (second "/tmp/inbox-second/")
           (noema-agent-inbox--roots (list first second))
           (noema-agent-inbox--results (make-hash-table :test #'equal))
           read refreshed)
      (puthash first '((names . [((name . "quiet") (sessionId . "sid-quiet"))
                                 ((name . "approval") (sessionId . "sid-approval")
                                  (attentionReason . "permission"))]))
               noema-agent-inbox--results)
      (puthash second '((names . [((name . "failure") (sessionId . "sid-failure")
                                    (attentionReason . "failed") (unread . t))]))
               noema-agent-inbox--results)
      (cl-letf (((symbol-function 'noema-agent-acp-sessions) (lambda (&optional _root) nil))
                ((symbol-function 'noema-sessions--mark-read)
                 (lambda (root name done)
                   (setq read (list root name))
                   (funcall done t)))
                ((symbol-function 'noema-agent-inbox--queue-update)
                 (lambda (all root) (setq refreshed (list all root)))))
        (noema-agent-inbox--render)
        (goto-char (point-min))
        (noema-agent-inbox-next-attention)
        (should (equal (plist-get (noema-agent-inbox--selected) :name) "failure"))
        (noema-agent-inbox-mark-read)
        (should (equal read (list second "failure")))
        (should (equal refreshed (list nil second)))
        (noema-agent-inbox-next-attention)
        (should (equal (plist-get (noema-agent-inbox--selected) :name) "approval"))
        (noema-agent-inbox-next-attention)
        (should (equal (plist-get (noema-agent-inbox--selected) :name) "failure"))))))

(ert-deftest noema-agent-inbox-coalesces-visible-events-and-catches-up-after-hide ()
  "Live events redraw once; Run events query once; hidden changes wait."
  (let ((buffer (generate-new-buffer noema-agent-inbox--buffer-name))
        (scheduled 0) (renders 0) (queries 0))
    (unwind-protect
        (save-window-excursion
          (switch-to-buffer buffer)
          (with-current-buffer buffer
            (noema-agent-inbox-mode)
            (setq noema-agent-inbox--results (make-hash-table :test #'equal)
                  noema-agent-inbox--request-serials (make-hash-table :test #'equal))
            (noema-agent-inbox--subscribe))
          (cl-letf (((symbol-function 'run-with-timer)
                     (lambda (&rest _) (cl-incf scheduled) (timer-create)))
                    ((symbol-function 'noema-agent-inbox--render)
                     (lambda () (cl-incf renders)))
                    ((symbol-function 'noema-agent-inbox-refresh)
                     (lambda (&optional _rescan) (cl-incf queries))))
            (noema-agent-inbox--session-changed nil)
            (noema-agent-inbox--session-changed nil)
            (should (= scheduled 1))
            (noema-agent-inbox--timer-fire buffer)
            (should (= renders 1))
            (should (= queries 0))
            (noema-agent-inbox--session-changed nil)
            (noema-agent-inbox--worker-changed nil 'finished)
            (noema-agent-inbox--worker-changed nil 1)
            (should (= scheduled 2))
            (noema-agent-inbox--timer-fire buffer)
            (should (= queries 1))
            (switch-to-buffer (get-buffer-create " *noema-inbox-hidden-test*"))
            (noema-agent-inbox--worker-changed nil 0)
            (should (= scheduled 2))
            (should-not (memq #'noema-agent-inbox--session-changed
                              noema-agent-acp-changed-functions))
            (switch-to-buffer buffer)
            (with-current-buffer buffer (noema-agent-inbox--shown nil))
            (should (= scheduled 3))
            (noema-agent-inbox--timer-fire buffer)
            (should (= queries 2))
            (noema-agent-inbox--worker-changed nil 1)
            (switch-to-buffer (get-buffer-create " *noema-inbox-hidden-test*"))
            (noema-agent-inbox--timer-fire buffer)
            (should (= queries 2))
            (should-not (memq #'noema-agent-inbox--session-changed
                              noema-agent-acp-changed-functions))
            (switch-to-buffer buffer)
            (with-current-buffer buffer (noema-agent-inbox--shown nil))
            (noema-agent-inbox--timer-fire buffer)
            (should (= queries 3))))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (when-let* ((hidden (get-buffer " *noema-inbox-hidden-test*")))
        (kill-buffer hidden)))))

(ert-deftest noema-agent-inbox-worker-refreshes-only-its-project ()
  "A worker event preserves unrelated rows and queries one Project."
  (let ((buffer (generate-new-buffer noema-agent-inbox--buffer-name))
        (first "/tmp/inbox-first/") (second "/tmp/inbox-second/")
        (third "/tmp/inbox-new/")
        requests)
    (unwind-protect
        (save-window-excursion
          (switch-to-buffer buffer)
          (with-current-buffer buffer
            (noema-agent-inbox-mode)
            (setq noema-agent-inbox--roots (list first second)
                  noema-agent-inbox--results (make-hash-table :test #'equal)
                  noema-agent-inbox--request-serials (make-hash-table :test #'equal))
            (puthash second '((names . [((name . "unrelated"))]))
                     noema-agent-inbox--results))
          (cl-letf (((symbol-function 'run-with-timer)
                     (lambda (&rest _) (timer-create)))
                    ((symbol-function 'noema-agent-inbox--project-root)
                     (lambda (path) path))
                    ((symbol-function 'noema-agent-inbox--render)
                     (lambda () nil))
                    ((symbol-function 'noema-sessions--api)
                     (lambda (_channel body callback)
                       (push (cons (alist-get 'root body) callback) requests))))
            (noema-agent-inbox--worker-changed
             (noema-agent-worker--create :root first) 'finished)
            (noema-agent-inbox--worker-changed
             (noema-agent-worker--create :root first) 1)
            (noema-agent-inbox--timer-fire buffer)
            (should (equal (mapcar #'car requests) (list first)))
            (with-current-buffer buffer
              (should (equal (noema-sessions--string
                              (aref (noema-sessions--get
                                     (gethash second noema-agent-inbox--results)
                                     "names") 0) "name")
                             "unrelated"))
              (should (equal noema-agent-inbox--pending (list first))))
            (switch-to-buffer (get-buffer-create " *noema-inbox-new-root-test*"))
            (noema-agent-inbox--worker-changed
             (noema-agent-worker--create :root third) 'finished)
            (with-current-buffer buffer
              (should (member third noema-agent-inbox--roots)))
            (should (= (length requests) 1))
            (switch-to-buffer buffer)
            (with-current-buffer buffer (noema-agent-inbox--shown nil))
            (noema-agent-inbox--timer-fire buffer)
            (should (= (length requests) 4))))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (when-let* ((hidden (get-buffer " *noema-inbox-new-root-test*")))
        (kill-buffer hidden)))))

(ert-deftest noema-agent-inbox-ignores-older-incremental-response ()
  "A slow earlier response for one Project cannot replace its newer state."
  (with-temp-buffer
    (noema-agent-inbox-mode)
    (let ((root "/tmp/inbox-one/") callbacks)
      (setq noema-agent-inbox--roots (list root))
      (cl-letf (((symbol-function 'noema-agent-inbox--render) (lambda () nil))
                ((symbol-function 'noema-sessions--api)
                 (lambda (_channel _body callback) (push callback callbacks))))
        (noema-agent-inbox-refresh)
        (let ((initial (car callbacks)))
          (noema-agent-inbox--refresh-roots (list root))
          (let ((older (car callbacks)))
            (noema-agent-inbox--refresh-roots (list root))
            (funcall (car callbacks)
                     '((names . [((name . "newest"))])) nil)
            (funcall older '((names . [((name . "older"))])) nil)
            (funcall initial '((names . [((name . "initial"))])) nil)
            (should (equal (noema-sessions--string
                            (aref (noema-sessions--get
                                   (gethash root noema-agent-inbox--results)
                                   "names") 0) "name")
                           "newest"))))))))

(ert-deftest noema-agent-worker-attention-event-carries-worker-and-count ()
  "Attention changes give the Inbox a signal after the count updates."
  (let ((noema-agent-worker--attention-count 0)
        (noema-agent-worker-attention-changed-functions nil)
        events)
    (add-hook 'noema-agent-worker-attention-changed-functions
              (lambda (worker count) (push (list worker count) events)))
    (cl-letf (((symbol-function 'noema-agent-worker--notify)
               (lambda (&rest _) nil)))
      (noema-agent-worker--attention-note 1 'test-worker)
      (noema-agent-worker--attention-note -1 'test-worker)
      (noema-agent-worker--attention-note -1 'test-worker))
    (should (equal (nreverse events)
                   '((test-worker 1) (test-worker 0))))))

(provide 'noema-agent-inbox-tests)
;;; noema-agent-inbox-tests.el ends here
