;;; check-native-agenda-actions.el --- Emacs to real host check -*- lexical-binding: t; -*-
;; Invoked by check-native-agenda.mjs with a disposable project and host.
(require 'cl-lib)
(require 'json)
(require 'url)
(when (equal (getenv "NOEMA_AGENDA_ROUTED_TEST") "1")
  (let ((root (expand-file-name "../../.." (file-name-directory load-file-name))))
    (dolist (directory '("lisp/remote" "lisp/remote/backend"))
      (add-to-list 'load-path (expand-file-name directory root))))
  (require 'remote-framework))
(require 'noema-agenda)

(defun noema-agenda-smoke--call (operation body callback)
  (let* ((url-request-method "POST")
         (url-request-extra-headers '(("Content-Type" . "application/json")))
         (url-proxy-services nil)
         (url-request-data
          (encode-coding-string
           (json-encode `((channel . ,(concat "aaronnote:api:agenda:" operation))
                          (args . ,(vector body)))) 'utf-8))
         (reply (url-retrieve-synchronously (concat (getenv "NOEMA_AGENDA_TEST_URL") "/api") t t 30))
         result)
    (unless reply (error "Host did not answer %s" operation))
    (unwind-protect
        (with-current-buffer reply
          (goto-char url-http-end-of-headers)
          (setq result (json-parse-buffer :object-type 'alist :array-type 'array
                                         :null-object nil :false-object :json-false))
          (unless (= url-http-response-status 200) (error "%s failed: %S" operation result)))
      (kill-buffer reply))
    (funcall callback result nil)))

(defun noema-agenda-smoke--task (title)
  (or (seq-find (lambda (todo) (equal title (noema-agenda--get todo 'text)))
                (noema-agenda--list (noema-agenda--get noema-agenda--snapshot 'todos)))
      (error "Task absent: %s" title)))

(defun noema-agenda-smoke--select (title)
  (goto-char (point-min))
  (search-forward title)
  (noema-agenda-item-at-point))

(with-temp-buffer
  (noema-agenda-mode)
  (setq noema-agenda--from "2026-09-15"
        noema-agenda--scopes (list "knowledge" (getenv "NOEMA_AGENDA_TEST_SCOPE")))
  (cl-letf (((symbol-function 'noema-agenda--call) #'noema-agenda-smoke--call)
            ((symbol-function 'org-mode) (lambda (&rest _) (error "Org source conversion")))
            ((symbol-function 'org-agenda-list) (lambda (&rest _) (error "Org source scanner"))))
    (noema-agenda-refresh)
    (noema-agenda-capture "Emacs capture A" (getenv "NOEMA_AGENDA_TEST_SCOPE"))
    (noema-agenda-capture "Emacs 捕获 B" (getenv "NOEMA_AGENDA_TEST_SCOPE"))
    (noema-agenda-refresh)
    (noema-agenda-todos)
    (noema-agenda-smoke--select "Emacs capture A")
    (noema-agenda-mark)
    (noema-agenda-smoke--select "Emacs 捕获 B")
    (noema-agenda-mark)
    (noema-agenda-bulk '((op . "complete")))
    (cl-assert (null noema-agenda--marks))
    (noema-agenda-refresh)
    (dolist (title '("Emacs capture A" "Emacs 捕获 B"))
      (cl-assert (equal "done" (noema-agenda--get (noema-agenda-smoke--task title) 'status))))
    (noema-agenda--patch (noema-agenda-smoke--task "Emacs capture A") '((status . "todo")))
    (noema-agenda-refresh)
    (noema-agenda-smoke--select "Emacs capture A")
    (noema-agenda-schedule "2026-09-17 09:30")
    (noema-agenda-refresh)
    (cl-assert (equal "2026-09-17 09:30"
                      (noema-agenda--get (noema-agenda--get (noema-agenda-smoke--task "Emacs capture A") 'canon) 'sche)))
    (noema-agenda-smoke--select "Emacs capture A")
    (noema-agenda-clock-in)
    (noema-agenda-refresh)
    (cl-assert (= 1 (length (noema-agenda--running-clocks))))
    (noema-agenda-clocktable)
    (cl-assert (string-match-p "Running: Emacs capture A" (buffer-string)))
    (noema-agenda-clock-out (car (noema-agenda--running-clocks)))
    (noema-agenda-refresh)
    (cl-assert (null (noema-agenda--running-clocks)))
    (noema-agenda-todos)
    (noema-agenda-smoke--select "Emacs capture A")
    (noema-agenda-dependency (noema-agenda-smoke--task "Emacs 捕获 B"))
    (noema-agenda-refresh)
    (cl-assert (equal (noema-agenda--get (noema-agenda-smoke--task "Emacs capture A") 'deps)
                      (vector (noema-agenda--get (noema-agenda-smoke--task "Emacs 捕获 B") 'uid))))
    (noema-agenda-smoke--select "Explore a coupling argument")
    (noema-agenda-progress "37.5")
    (noema-agenda-refresh)
    (cl-assert (equal "37.5" (noema-agenda--get (noema-agenda--get (noema-agenda-smoke--task "Explore a coupling argument") 'canon) 'progress)))
    (cl-assert (string-match-p (regexp-quote "Explore a coupling argument [37.5%]") (buffer-string)))
    (noema-agenda-smoke--select "Explore a coupling argument")
    (noema-agenda-clock-in)
    (noema-agenda-refresh)
    (cl-assert (equal (noema-agenda--get (car (noema-agenda--running-clocks)) 'todoId)
                      (noema-agenda--get (noema-agenda-smoke--task "Explore a coupling argument") 'uid)))
    (noema-agenda-smoke--select "Review the evidence and choose a branch")
    (noema-agenda-clock-in)
    (noema-agenda-refresh)
    (cl-assert (= 1 (length (noema-agenda--running-clocks))))
    (cl-assert (equal (noema-agenda--get (car (noema-agenda--running-clocks)) 'todoId)
                      (noema-agenda--get (noema-agenda-smoke--task "Review the evidence and choose a branch") 'uid)))
    (noema-agenda-clock-out (car (noema-agenda--running-clocks)))
    (noema-agenda-refresh)
    (cl-assert (null (noema-agenda--running-clocks)))
    (princ "Native Emacs capture/bulk/schedule/clock/dependency: passed\n")))
