import type { ResearchIndexer } from "./research-notebook.mjs";

export type ResearchRuntimeProvider = {
	resolveCell(args: { root: string; notebookId: string; cellId: string }): Promise<{ notebookId: string; cellId: string; path: string; revision: string }>;
  promoteSession(args: { root: string; session: Record<string, any> }): Promise<Record<string, any>>;
  sessions(args: { root: string; workstreamId?: string; adapter?: string; limit?: number }): Promise<Record<string, any>[]>;
  session(args: { root: string; id: string }): Promise<Record<string, any>>;
  beginManualIntervention(args: { root: string; intervention: Record<string, any> }): Promise<Record<string, any>>;
  endManualIntervention(args: { root: string; intervention: Record<string, any> }): Promise<Record<string, any>>;
  manualIntervention(args: { root: string; id: string }): Promise<Record<string, any>>;
  prepareRun(args: { root: string; run: Record<string, any> }): Promise<Record<string, any>>;
  runs(args: { root: string; workstreamId?: string; sessionId?: string; limit?: number }): Promise<Record<string, any>[]>;
  run(args: { root: string; id: string }): Promise<Record<string, any>>;
  liveRun(args: { root: string; id: string; after?: number; limit?: number }): Promise<Record<string, any>>;
  requestRunCancellation(args: { root: string; cancellation: Record<string, any> }): Promise<Record<string, any>>;
  failPreparedRun(args: { root: string; failure: Record<string, any> }): Promise<Record<string, any>>;
  artifact(args: { root: string; id: string }): Promise<Record<string, any>>;
  readArtifact(args: { root: string; id: string }): Promise<Record<string, any>>;
  importArtifact(args: { root: string; artifact: Record<string, any> }): Promise<Record<string, any>>;
  artifactLinks(args: { root: string; workstreamId?: string; notebookId?: string; workNodeId?: string; runId?: string; limit?: number }): Promise<Record<string, any>[]>;
  indexArtifactCorpus(args: { root: string; index: Record<string, any> }): Promise<Record<string, any>>;
  indexArtifactFiles(args: { root: string; index: Record<string, any> }): Promise<Record<string, any>>;
  searchArtifactBlocks(args: { root: string; search: Record<string, any> }): Promise<Record<string, any>[]>;
  readArtifactBlock(args: { root: string; id: string }): Promise<Record<string, any>>;
  createCapture(args: { root: string; capture: Record<string, any> }): Promise<Record<string, any>>;
  captures(args: { root: string; limit?: number }): Promise<Record<string, any>[]>;
  acquireLease(args: { root: string; lease: Record<string, any> }): Promise<Record<string, any>>;
  renewLease(args: { root: string; lease: Record<string, any> }): Promise<Record<string, any>>;
  expireLeases(args: { root: string }): Promise<Record<string, any>>;
  attachRun(args: { root: string; attachment: Record<string, any> }): Promise<Record<string, any>>;
  startRun(args: { root: string; start: Record<string, any> }): Promise<Record<string, any>>;
  reportWorkerEvents(args: { root: string; events: Record<string, any> }): Promise<Record<string, any>[]>;
  requestWorkerPermission(args: { root: string; permission: Record<string, any> }): Promise<Record<string, any>>;
  requestWorkerInput(args: { root: string; input: Record<string, any> }): Promise<Record<string, any>>;
  permission(args: { root: string; id: string }): Promise<Record<string, any>>;
  decidePermission(args: { root: string; decision: Record<string, any> }): Promise<Record<string, any>>;
  inputRequest(args: { root: string; id: string }): Promise<Record<string, any>>;
  respondInput(args: { root: string; response: Record<string, any> }): Promise<Record<string, any>>;
  attention(args: { root: string }): Promise<{ permissions: Record<string, any>[]; inputRequests: Record<string, any>[]; inputRuns: Record<string, any>[]; proposals: Record<string, any>[] }>;
  createProposal(args: { root: string; proposal: Record<string, any> }): Promise<Record<string, any>>;
  proposal(args: { root: string; id: string }): Promise<Record<string, any>>;
  proposals(args: { root: string; workstreamId?: string; status?: string; limit?: number }): Promise<Record<string, any>[]>;
  beginProposalAcceptance(args: { root: string; review: Record<string, any> }): Promise<{ proposal: Record<string, any> }>;
  reviewProposal(args: { root: string; review: Record<string, any> }): Promise<Record<string, any>>;
  finding(args: { root: string; id: string }): Promise<Record<string, any>>;
  findings(args: { root: string; workstreamId?: string; status?: string; query?: string; limit?: number; includeLocal?: boolean }): Promise<Record<string, any>[]>;
  researchIR(args: { root: string; workstreamId: string; limit?: number }): Promise<Record<string, any>[]>;
  problemModels(args: { root: string; workstreamId: string; limit?: number }): Promise<Record<string, any>[]>;
  createWorkstreamExport(args: { root: string; export: Record<string, any> }): Promise<Record<string, any>>;
  createTask(args: { root: string; task: Record<string, any> }): Promise<Record<string, any>>;
  task(args: { root: string; id: string }): Promise<Record<string, any>>;
  tasks(args: { root: string; workstreamId?: string; state?: string; limit?: number; includeLocal?: boolean }): Promise<Record<string, any>[]>;
  transitionTask(args: { root: string; transition: Record<string, any> }): Promise<Record<string, any>>;
  createJob(args: { root: string; job: Record<string, any> }): Promise<Record<string, any>>;
  job(args: { root: string; id: string }): Promise<Record<string, any>>;
  jobs(args: { root: string; workstreamId?: string; taskId?: string; state?: string; limit?: number }): Promise<Record<string, any>[]>;
  claimJob(args: { root: string; claim: Record<string, any> }): Promise<Record<string, any>>;
  startJob(args: { root: string; lease: Record<string, any> }): Promise<Record<string, any>>;
  renewJobLease(args: { root: string; lease: Record<string, any> }): Promise<Record<string, any>>;
  expireJobLeases(args: { root: string; workstreamId?: string }): Promise<Record<string, any>>;
  completeJob(args: { root: string; completion: Record<string, any> }): Promise<Record<string, any>>;
  failJob(args: { root: string; completion: Record<string, any> }): Promise<Record<string, any>>;
  reportJobUnresolved(args: { root: string; completion: Record<string, any> }): Promise<Record<string, any>>;
  retryJob(args: { root: string; retry: Record<string, any> }): Promise<Record<string, any>>;
  invocation(args: { root: string; id: string }): Promise<Record<string, any>>;
  invocations(args: { root: string; jobId: string; limit?: number }): Promise<Record<string, any>[]>;
  registerSchedulerWorker(args: { root: string; worker: Record<string, any> }): Promise<Record<string, any>>;
  schedulerWorker(args: { root: string; id: string }): Promise<Record<string, any>>;
  schedulerWorkers(args: { root: string; state?: string; limit?: number }): Promise<Record<string, any>[]>;
  createDelegation(args: { root: string; delegation: Record<string, any> }): Promise<Record<string, any>>;
  delegation(args: { root: string; id: string }): Promise<Record<string, any>>;
  delegations(args: { root: string; workstreamId?: string; parentTaskId?: string; childTaskId?: string; limit?: number }): Promise<Record<string, any>[]>;
  indexHistory(args: { root: string; sources: Record<string, any>[] }): Promise<Record<string, any>>;
  searchHistory(args: { root: string; query: string; projectRoot?: string; source?: string; limit?: number }): Promise<Record<string, any>[]>;
  peekHistory(args: { root: string; id: string; maxRunes?: number }): Promise<Record<string, any>>;
  readHistory(args: { root: string; id: string }): Promise<Record<string, any>>;
};

export function createKernelResearchProvider(options: {
  baseUrl: string;
  fetchImpl?: (url: string, init: RequestInit) => Promise<Response>;
  timeoutMs?: number;
}): ResearchIndexer & ResearchRuntimeProvider;
