export function createJupyterApiHandlers(service) {
  return {
    "aaronnote:api:jupyter-cell:kernels": (body) => service.kernels(body || {}),
    "aaronnote:api:jupyter-cell:execute": (body) => service.execute(body || {}),
    "aaronnote:api:jupyter-cell:open-script": (body) => service.openScript(body || {}),
    "aaronnote:api:jupyter-cell:read-script-cell": (body) => service.readScriptCell(body || {}),
    "aaronnote:api:jupyter:document-snapshot": (body) => service.documentSnapshot(body || {}),
    "aaronnote:api:jupyter:document-mutate": (body) => service.documentMutate(body || {}),
    "aaronnote:api:jupyter:document-execute": (body) => service.documentExecute(body || {}),
    "aaronnote:api:jupyter:manager-snapshot": () => service.managerSnapshot(),
    "aaronnote:api:jupyter:script-snapshot": (body) => service.documentSnapshot(body || {}),
    "aaronnote:api:jupyter:script-action": (body) => service.scriptAction(body || {}),
    "aaronnote:api:jupyter:session-select": (body) => service.sessionSelect(body || {}),
    "aaronnote:api:jupyter:kernel-control": (body) => service.kernelControl(body || {}),
    "aaronnote:api:jupyter:board-open": () => service.openBoard(),
    "aaronnote:api:jupyter-cell:execute-script-cell": (body) => service.executeScriptCell(body || {}),
    "aaronnote:api:jupyter-cell:clear-script-cell-output": (body) => service.clearScriptCellOutput(body || {}),
    "aaronnote:api:jupyter-cell:delete-script-cell": (body) => service.deleteScriptCell(body || {}),
    "aaronnote:api:jupyter-cell:save-script-cell-output-ui": (body) => service.saveScriptCellOutputUi(body || {}),
    "aaronnote:api:jupyter-cell:clear-all-outputs": (body) => service.clearAllOutputs(body || {}),
    "aaronnote:api:jupyter-cell:variables": (body) => service.variables(body || {}),
    "aaronnote:api:jupyter-cell:input-reply": (body) => service.inputReply(body || {}),
    "aaronnote:api:jupyter-cell:complete": (body) => service.complete(body || {}),
    "aaronnote:api:jupyter-cell:inspect": (body) => service.inspect(body || {}),
    "aaronnote:api:jupyter-cell:is-complete": (body) => service.isComplete(body || {}),
    "aaronnote:api:jupyter-cell:history": (body) => service.history(body || {}),
    "aaronnote:api:jupyter-cell:comm-info": (body) => service.commInfo(body || {}),
    "aaronnote:api:jupyter-cell:kernel-status": (body) => service.kernelStatus(body || {}),
    "aaronnote:api:jupyter-cell:restart": (body) => service.restart(body || {}),
    "aaronnote:api:jupyter-cell:interrupt": (body) => service.interrupt(body || {}),
    "aaronnote:api:jupyter-cell:shutdown": (body) => service.shutdownKernel(body || {}),
    "aaronnote:api:jupyter-cell:server-list": (body) => service.serverList(body || {}),
    "aaronnote:api:jupyter-cell:server-read": (body) => service.serverRead(body || {}),
    "aaronnote:api:jupyter-cell:server-write": (body) => service.serverWrite(body || {}),
    "aaronnote:api:jupyter-cell:tasks": () => service.listTasks(),
    "aaronnote:api:jupyter-cell:cleanup": (body) => service.cleanup(body || {}),
  };
}
